### ISSUE TITLE
Connection issue from SS to CS via port 4001

### ISSUE THREAD

**Issue by VirajAttanayake** [nordic-institute/X-Road#1046]
I used Ansible to install xroad on  LXD (As shown the demo **X Road Academy Session 1: Setting up a local X-Road development environment**).  I get below error when register the Auth certificate from Security server.

I see an error in SS logs  `org.apache.http.conn.HttpHostConnectException: Connect to xroad-lxd-cs.lxd:4001 [xroad-lxd-cs.lxd/10.152.99.241, xroad-lxd-cs.lxd/fd42:bf5d:7d15:1539:216:3eff:fee2:5491] failed: Connection refused (Connection refused)` however when I checked the CS (xroad-lxd-cs.lxd), I can see a process is running on port 4001 (when checked with netstat -nplt) 

![image](https://user-images.githubusercontent.com/16677999/133782071-91b82c22-0a23-4bf2-b6ad-917890020762.png)

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

What's the result when you try to connect to the Central Server from the Security Server LXD container? First, get a shell inside the Security Server container ( `lxc exec <SS_CONTAINER_NAME> bash`) and then use `telnet`:

```bash
telnet xroad-lxd-cs.lxd 4001
```

Also, what's the result if you use the Central Server IP instead of the DNS name?

```bash
telnet 10.152.99.241 4001
```

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Thanks for the quick response.  Please check below, The telnet cant connect, but I see a process listening in port 4001 in CS container,

![image](https://user-images.githubusercontent.com/16677999/133793223-fba90d3f-0b42-4603-81b1-dffd922b2f99.png)

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

What's the result if you run the `telnet` commands (using DNS name and IP address) on your host machine?

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,
I guess you mean the container host machine ? I can get in using telnet .
![image](https://user-images.githubusercontent.com/16677999/133795130-d80bd849-7849-4eba-9303-872a6184560e.png)

Thanks
Viraj

**Comment by petkivim** [comment]
Hi @VirajAttanayake 

Yes, I meant the container host machine. Since the connection from the container host machine is working, it seems to be some kind of an LXD networking issue. Did you configure LXD according to the [instructions](https://github.com/nordic-institute/X-Road/tree/develop/ansible#using-lxd-hosts) before running the Ansible script?

Regards,
Petteri

**Comment by VirajAttanayake** [comment]
Hi Petteri,

Yes, I followed the manual and the Demo Video. However I can ping the CS from SS.

![image](https://user-images.githubusercontent.com/16677999/133796702-343019bc-70f9-4c1a-9068-65a37882193c.png)


Regards,
Viraj

**Comment by VirajAttanayake** [comment]
HI Petteri,

The ss1 lxd container now has access to cs lxd container. But the service on port 4001 is not working. Please see the logs signer.logs.

![image](https://user-images.githubusercontent.com/16677999/133889271-bbd014e8-0832-46b0-9c78-b029901aff92.png)
```

2021-09-18T04:02:45.704Z ERROR [main] e.r.x.common.SystemPropertiesLoader - Configuration loading failed
java.io.FileNotFoundException: None of the following configuration files were found: /etc/xroad/conf.d/center.ini, /etc/xroad/conf.d/proxy.ini, /etc/xroad/conf.d/confproxy.ini
        at ee.ria.xroad.common.SystemPropertiesLoader.loadMutuallyAlternativeFilesInEntryOrder(SystemPropertiesLoader.java:344)
        at ee.ria.xroad.common.SystemPropertiesLoader.load(SystemPropertiesLoader.java:270)
        at ee.ria.xroad.signer.SignerMain.<clinit>(SignerMain.java:73)
2021-09-18T04:02:45.728Z INFO  [main] ee.ria.xroad.common.Version - xroad-signer 6.26.0 (OpenJDK Runtime Environment Private Build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
2021-09-18T04:02:45.735Z INFO  [main] ee.ria.xroad.signer.SignerMain - Starting Signer on port 5558...
2021-09-18T04:02:46.674Z WARN  [Signer-akka.actor.default-dispatcher-6] akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
2021-09-18T04:02:46.982Z INFO  [main] org.eclipse.jetty.util.log - Logging initialized @1649ms to org.eclipse.jetty.util.log.Slf4jLog
2021-09-18T04:02:47.265Z INFO  [main] ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5559
2021-09-18T04:02:47.268Z INFO  [main] org.eclipse.jetty.server.Server - jetty-9.4.36.v20210114; built: 2021-01-14T16:44:28.689Z; git: 238ec6997c7806b055319a6d11f8ae7564adc0de; jvm 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10
2021-09-18T04:02:47.314Z INFO  [main] o.e.jetty.server.AbstractConnector - Started AdminPort@4c4d27c8{HTTP/1.1, (http/1.1)}{127.0.0.1:5559}
2021-09-18T04:02:47.314Z INFO  [main] org.eclipse.jetty.server.Server - Started @1981ms
2021-09-18T04:02:47.392Z WARN  [Signer-akka.actor.default-dispatcher-11] e.r.x.c.c.globalconf.GlobalConfImpl - Global configuration is invalid
ee.ria.xroad.common.CodedException: MalformedGlobalConf: File 'files' is missing
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getConfigurationFiles(ConfigurationDirectoryV2.java:233)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.eachFile(ConfigurationDirectoryV2.java:222)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.verifyUpToDate(ConfigurationDirectoryV2.java:312)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.verifyUpToDate(CachingConfigurationDirectory.java:130)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.isValid(GlobalConfImpl.java:109)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.isValid(GlobalConf.java:175)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.handleReload(OcspClientWorker.java:137)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.onReceive(OcspClientWorker.java:115)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:47.392Z ERROR [Signer-akka.actor.default-dispatcher-11] e.r.x.s.certmanager.OcspClientWorker - Global configuration is not valid, skipping change detection
2021-09-18T04:02:52.275Z INFO  [Signer-akka.actor.default-dispatcher-6] e.r.x.s.certmanager.OcspClientWorker - OCSP-response refresh cycle started
2021-09-18T04:02:52.276Z WARN  [Signer-akka.actor.default-dispatcher-6] e.r.x.c.c.globalconf.GlobalConfImpl - Global configuration is invalid
ee.ria.xroad.common.CodedException: MalformedGlobalConf: File 'files' is missing
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getConfigurationFiles(ConfigurationDirectoryV2.java:233)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.eachFile(ConfigurationDirectoryV2.java:222)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.verifyUpToDate(ConfigurationDirectoryV2.java:312)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.verifyUpToDate(CachingConfigurationDirectory.java:130)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.isValid(GlobalConfImpl.java:109)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.isValid(GlobalConf.java:175)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.handleExecute(OcspClientWorker.java:196)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.onReceive(OcspClientWorker.java:113)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:52.281Z ERROR [Signer-akka.actor.default-dispatcher-11] e.r.x.c.c.g.ConfigurationDirectoryV2 - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier

java.io.FileNotFoundException: File '/etc/xroad/globalconf/instance-identifier' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2368)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2486)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2472)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.loadInstanceIdentifier(ConfigurationDirectoryV2.java:339)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getInstanceIdentifier(ConfigurationDirectoryV2.java:111)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.getInstanceIdentifier(CachingConfigurationDirectory.java:82)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.getInstanceIdentifier(GlobalConfImpl.java:121)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:184)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:136)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:150)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:130)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:85)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:496)
        at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:76)
        at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:56)
        at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:128)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:52.281Z ERROR [Signer-akka.actor.default-dispatcher-11] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: InternalError: Could not read instance identifier of this security server
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.loadInstanceIdentifier(ConfigurationDirectoryV2.java:343)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getInstanceIdentifier(ConfigurationDirectoryV2.java:111)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.getInstanceIdentifier(CachingConfigurationDirectory.java:82)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.getInstanceIdentifier(GlobalConfImpl.java:121)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:184)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:136)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:150)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:130)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:85)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:496)
        at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:76)
        at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:56)
        at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:128)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:52.281Z INFO  [Signer-akka.actor.default-dispatcher-11] ee.ria.xroad.signer.OcspClientJob - Next OCSP refresh scheduled in 1200 seconds
2021-09-18T04:02:52.282Z ERROR [Signer-akka.actor.default-dispatcher-11] e.r.x.c.c.g.ConfigurationDirectoryV2 - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.io.FileNotFoundException: File '/etc/xroad/globalconf/instance-identifier' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:2368)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2486)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:2472)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.loadInstanceIdentifier(ConfigurationDirectoryV2.java:339)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getInstanceIdentifier(ConfigurationDirectoryV2.java:111)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.getInstanceIdentifier(CachingConfigurationDirectory.java:82)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.getInstanceIdentifier(GlobalConfImpl.java:121)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:184)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:136)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:150)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:130)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:85)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:496)
        at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:78)
        at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:56)
        at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:128)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:52.282Z ERROR [Signer-akka.actor.default-dispatcher-11] e.r.x.c.c.g.GlobalConfExtensions - Exception while fetching ocsp fetch interval configuration
ee.ria.xroad.common.CodedException: InternalError: Could not read instance identifier of this security server
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.loadInstanceIdentifier(ConfigurationDirectoryV2.java:343)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationDirectoryV2.getInstanceIdentifier(ConfigurationDirectoryV2.java:111)
        at ee.ria.xroad.common.conf.globalconf.CachingConfigurationDirectory.getInstanceIdentifier(CachingConfigurationDirectory.java:82)
        at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.getInstanceIdentifier(GlobalConfImpl.java:121)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceIdentifier(GlobalConf.java:184)
        at ee.ria.xroad.common.conf.globalconf.GlobalConf.getInstanceFile(GlobalConf.java:136)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchIntervalConfigurationPath(GlobalConfExtensions.java:150)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getFetchInterval(GlobalConfExtensions.java:130)
        at ee.ria.xroad.common.conf.globalconfextension.GlobalConfExtensions.getOcspFetchInterval(GlobalConfExtensions.java:85)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.getNextOcspFetchIntervalSeconds(OcspClientWorker.java:496)
        at ee.ria.xroad.signer.OcspClientJob.getNextDelay(OcspClientJob.java:78)
        at ee.ria.xroad.signer.util.VariableIntervalPeriodicJob.onReceive(VariableIntervalPeriodicJob.java:56)
        at ee.ria.xroad.signer.OcspClientJob.onReceive(OcspClientJob.java:128)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-09-18T04:02:52.282Z INFO  [Signer-akka.actor.default-dispatcher-11] ee.ria.xroad.signer.OcspClientJob - OCSP-response refresh cycle failed due to invalid global configuration, switching to global configuration recovery schedule
2021-09-18T04:03:00.980Z INFO  [Signer-shutdown-hook-2] ee.ria.xroad.signer.SignerMain - Signer shutting down...
2021-09-18T04:03:01.001Z INFO  [Signer-shutdown-hook-2] o.e.jetty.server.AbstractConnector - Stopped AdminPort@4c4d27c8{HTTP/1.1, (http/1.1)}{127.0.0.1:5559}
2021-09-18T04:03:01.574Z INFO  [main] ee.ria.xroad.common.Version - xroad-signer 6.26.0 (OpenJDK Runtime Environment Private Build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
2021-09-18T04:03:01.577Z INFO  [main] ee.ria.xroad.signer.SignerMain - Starting Signer on port 5558...
2021-09-18T04:03:02.933Z WARN  [Signer-akka.actor.default-dispatcher-6] akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
2021-09-18T04:03:03.350Z INFO  [main] org.eclipse.jetty.util.log - Logging initialized @2283ms to org.eclipse.jetty.util.log.Slf4jLog
2021-09-18T04:03:04.018Z INFO  [Signer-akka.actor.default-dispatcher-6] ee.ria.xroad.signer.OcspRetrievalJob - OCSP-retrieval configured to be inactive, job auto-scheduling disabled
2021-09-18T04:03:04.019Z INFO  [Signer-akka.actor.default-dispatcher-6] ee.ria.xroad.signer.OcspRetrievalJob - OCSP-retrieval configured to be inactive, job auto-scheduling disabled
2021-09-18T04:03:04.039Z INFO  [main] ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5559
2021-09-18T04:03:04.058Z INFO  [main] org.eclipse.jetty.server.Server - jetty-9.4.36.v20210114; built: 2021-01-14T16:44:28.689Z; git: 238ec6997c7806b055319a6d11f8ae7564adc0de; jvm 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10
2021-09-18T04:03:04.119Z INFO  [main] o.e.jetty.server.AbstractConnector - Started AdminPort@758c83d8{HTTP/1.1, (http/1.1)}{127.0.0.1:5559}
2021-09-18T04:03:04.121Z INFO  [main] org.eclipse.jetty.server.Server - Started @3054ms
```
