### ISSUE TITLE
Strange on external Load Balancer

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#106]
Hi everyone,
I'm working on Xroad External Load Balancer following this guide: https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md. So, I have 2 SS provider to balancing are located on 10.0.14.233 and 10.0.14.234, and 1 nginx for LB server is located on 10.0.14.237.
After configuring complete, The LB seem work properly in about the 20 first minutes and proxy log my SS consumer like this:
2019-03-01 17:33:22,449 [qtp1532800776-1304] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-01 17:33:22,719 [qtp1532800776-1304] INFO  e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled
2019-03-01 17:33:25,722 [qtp1532800776-358] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:25,722 [qtp1532800776-358] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:25,722 [qtp1532800776-358] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:25,724 [qtp1532800776-358] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:25,727 [qtp1532800776-358] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-01 17:33:26,233 [qtp1532800776-358] INFO  e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled
2019-03-01 17:33:41,940 [qtp1532800776-1026] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:41,940 [qtp1532800776-1026] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:41,940 [qtp1532800776-1026] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:41,946 [qtp1532800776-1026] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:41,979 [qtp1532800776-1026] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-01 17:33:42,211 [qtp1532800776-1026] INFO  e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled
2019-03-01 17:33:45,520 [qtp1532800776-490] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:45,520 [qtp1532800776-490] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:45,521 [qtp1532800776-490] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:45,522 [qtp1532800776-490] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2019-03-01 17:33:45,534 [qtp1532800776-490] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-01 17:33:46,381 [qtp1532800776-490] INFO  e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled

Howerver, after that it does not work anymore, the proxy log on my SS consumer always show this:
2019-03-01 17:18:00,809 [qtp1532800776-547] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-01 17:18:01,257 [qtp1532800776-1460-soap] ERROR e.r.x.p.c.ClientMessageProcessor - onError()
ee.ria.xroad.common.CodedException: IOError: null
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:205) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:120) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.writeOcspResponses(ClientMessageProcessor.java:701) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.soap(ClientMessageProcessor.java:633) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder$MultipartHandler.body(SoapMessageDecoder.java:225) ~[proxy-1.0.jar:na]
	at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:133) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.readMultipart(SoapMessageDecoder.java:178) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.parse(SoapMessageDecoder.java:135) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.handleSoap(ClientMessageProcessor.java:596) [proxy-1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:275) ~[na:1.8.0_171]
	at java.io.PipedInputStream.receive(PipedInputStream.java:231) ~[na:1.8.0_171]
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_171]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_171]
	at ee.ria.xroad.common.util.MultipartEncoder.write(MultipartEncoder.java:184) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:118) ~[proxy-1.0.jar:na]
	... 12 common frames omitted
2019-03-01 17:18:01,257 [qtp1532800776-547] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (b415c910-014b-4eed-875d-2ac36ebe4a42)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.InternalError: Connection refused (Connection refused)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:172) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getOcspResponses(AuthTrustVerifier.java:152) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verifyAuthCert(AuthTrustVerifier.java:106) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:89) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_171]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_171]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_171]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_171]
	at ee.ria.xroad.common.util.CertHashBasedOcspResponderClient.getOcspResponsesFromServer(CertHashBasedOcspResponderClient.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.CertHashBasedOcspResponderClient.getOcspResponsesFromServer(CertHashBasedOcspResponderClient.java:78) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:169) ~[proxy-1.0.jar:na]
	... 32 common frames omitted

I change IP SS on central server to 10.0.13.234 and wait a few minutes then change it to 10.0.14.237 again, to make it works well in the 20 first minutes and then it still down again. It's so strange, I can not understand why the LB just only work on a period like that. I need your help, please see the log and tell me what should I do?
And here is my nginx LB configuration:
stream {
  log_format  basic   '$time_iso8601 $remote_addr '
                        '$protocol $status $bytes_sent $bytes_received '
                        '$session_time $upstream_addr '
                        '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';

    access_log      /var/log/nginx/tcp_acces  basic buffer=1k flush=5s;
    error_log /var/log/nginx/tcp_error.log error;

    upstream web_server {
       # hash   $remote_addr consistent;
   server 10.0.14.233:5500;
   server 10.0.14.234:5500;
 }

    server {
        listen 5500;
        proxy_pass web_server;
    }
}

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

In addition to port `5500` the LB must be configured to route requests to port `5577` too. Currently port `5577` is missing from your nginx configuration and it is causing your problems.

Security Servers use port `5500` to exchange message and port `5577` to exchange OCSP responses. Because the port `5577` is missing from your LB's configuration the client Security Server is not able to fetch OCSP responses from the cluster. Therefore, the client throws an error when cached OCSP responses expire and the client is not able to fetch new ones from the cluster. When you drop the LB between the client and the cluster, the client is able to fetch the OCSP response from the service provider Security Server and message exchange works again. Once you put the LB between the Security Servers, message exchange works until cached OCSP responses expire.

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Hi @petkivim,
Thank you so much for your answer, I added port 5577 to the LB configuration and it works properly. However the proxy log on my SS consumer always show error "Error while getting peer certificates" and "peer not authenticated" like this : 
2019-03-02 17:44:31,246 [qtp1747721875-86] INFO  e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connecting to https://10.0.14.237:5500/
2019-03-02 17:44:31,255 [qtp1747721875-86] ERROR e.r.x.p.c.AuthTrustVerifier - Error while getting peer certificates
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:440) ~[na:1.8.0_171]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:197) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2019-03-02 17:44:31,256 [qtp1747721875-86] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (b788098d-f16d-4a4f-af4b-cd20d32b0417)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed: Service provider did not send correct authentication certificate
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:200) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2019-03-02 17:44:31,256 [qtp1747721875-86-soap] ERROR e.r.x.p.c.ClientMessageProcessor - onError()
ee.ria.xroad.common.CodedException: IOError: null
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:205) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:120) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.writeOcspResponses(ClientMessageProcessor.java:701) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.soap(ClientMessageProcessor.java:633) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder$MultipartHandler.body(SoapMessageDecoder.java:225) ~[proxy-1.0.jar:na]
	at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:133) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.readMultipart(SoapMessageDecoder.java:178) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.parse(SoapMessageDecoder.java:135) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.handleSoap(ClientMessageProcessor.java:596) [proxy-1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:275) ~[na:1.8.0_171]
	at java.io.PipedInputStream.receive(PipedInputStream.java:231) ~[na:1.8.0_171]
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_171]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_171]
	at ee.ria.xroad.common.util.MultipartEncoder.write(MultipartEncoder.java:184) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:118) ~[proxy-1.0.jar:na]
	... 12 common frames omitted

In addition, I change IP SS on Central Server to 10.0.14.234, then check proxy log on the SS consumer again and no error is showed.

**Comment by nguyenhabkit** [comment]
Sorry @petkivim that is my fault in LB configuration!

Thank you so much!
Ha.
