### ISSUE TITLE
Intermittent SSLPeerUnverifiedExceptions

### ISSUE THREAD

**Issue by autero1** [nordic-institute/X-Road#1224]
We're intermittently seeing the following behaviour. Request to our internal security server takes ~30 secs and we have the following lines in the security server logs:  

```
2022-04-21T10:46:42.723Z INFO [xroad-proxy] [qtp1728266914-48869] e.r.x.p.c.AbstractClientProxyHandler - Received request from 10.55.123.135
2022-04-21T10:47:12.785Z ERROR [xroad-proxy] [qtp1728266914-48869] e.r.x.p.c.AuthTrustVerifier - Error while getting peer certificates
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:556)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:201)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:86)
2022-04-21T10:47:13.420Z INFO [xroad-proxy] [qtp1728266914-48869] e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled
```

As you can see, the request seems to eventually return ok (`Request successfully handled`), but takes ~30 secs. Majority of the requests go through ok.

We're uncertain as to what the root cause is - whether it's something in the security server itself or the service we're calling (personal identity service, DVV).

**Comment by vellotis** [comment]
Hey, @autero1. Looking into it.

- Has it been persistent all the time or after some sort of version/setup changes?
- How often does this occur in the logs?

**Comment by vellotis** [comment]
@autero1 it would be grateful if we could get a DEBUG level logging for `ee.ria.xroad.proxy.clientproxy`.
```xml
    <logger name="ee.ria.xroad.proxy.clientproxy" level="DEBUG" />
```

**Comment by vellotis** [comment]
@autero1, we are supposing that one of the (total of 2) DVV security servers is problematic. There is a race for creating a socket level connection between two target servers. From time to time the problematic target wins the race but TLS connection establishment times out in 30seconds. It is followed by trying another target as there is still time (default 60 sec). There is no problems with the second target and the whole procedure succeeds.

Can't say which of the targets is problematic. TRACE logging level will have this info available in the logs.

I suggest you contact the DVV to check if the services are healthy.

**Comment by autero1** [comment]
Thanks @vellotis , I think you're absolutely correct! Here's a redacted `TRACE` for one request taking 30+ secs:

```
2022-04-22T12:04:48.010Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AbstractClientProxyHandler - PERFORMANCE: 1650629088010: Received request from 10.55.123.135
2022-04-22T12:04:48.010Z INFO [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AbstractClientProxyHandler - Received request from 10.55.123.135
2022-04-22T12:04:48.222Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AbstractClientMessageProcessor - getServiceAddresses(SERVICE:XXX, null)
2022-04-22T12:04:48.225Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - addresses from context [https://XXXXv.xxx.xx:5500/, https://XXXX.xxx.xx:5500/] current thread id 53
2022-04-22T12:05:18.344Z ERROR [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - Error while getting peer certificates
2022-04-22T12:05:18.345Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Failed to connect to https://XXXXv.xxx.xx:5500/
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:556)
2022-04-22T12:05:18.660Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - get ocsp response from key conf
2022-04-22T12:05:18.663Z WARN [xroad-signer] [Signer-akka.actor.default-dispatcher-15] e.r.x.s.c.OcspResponseManager - Could not find certificate for hash xxx
2022-04-22T12:05:18.663Z WARN [xroad-signer] [Signer-akka.actor.default-dispatcher-15] e.r.x.s.c.OcspResponseManager - Could not acquire an OCSP response for certificate xxx
2022-04-22T12:05:18.667Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - ocsp response from key conf: null
2022-04-22T12:05:18.667Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - number of certs that still need ocsp responses: 1
2022-04-22T12:05:18.667Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - get ocsp responses from server XXXX.xxx.xx
2022-04-22T12:05:18.745Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AuthTrustVerifier - got ocsp responses, setting them to key conf
2022-04-22T12:05:18.783Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Connected to https://XXXX.xxx.xx:5500/
2022-04-22T12:05:18.783Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Store the fastest provider URI to cache https://XXXX.xxx.xx:5500/
2022-04-22T12:05:18.804Z INFO [xroad-signer] [Signer-akka.actor.default-dispatcher-17] e.r.x.s.p.h.GetMemberSigningInfoRequestHandler - Found suitable certificate for member 'SUBSYSTEM:XX/XXX/XXX' under key XXXXXXX
2022-04-22T12:05:20.426Z INFO [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AbstractClientProxyHandler - Request successfully handled (32416 ms)
2022-04-22T12:05:20.426Z TRACE [xroad-proxy] [qtp643570300-53] e.r.x.p.c.AbstractClientProxyHandler - PERFORMANCE: 1650629120426: 32416: Request handled
2022-04-22T12:05:20.429Z INFO [xroad-proxy] [qtp643570300-53] e.r.x.proxy.clientproxy.RequestLog - 10.55.123.135 - - [22/Apr/2022:12:04:48 +0000] "POST / HTTP/1.1" 200 6141 "-" "Java/11.0.13" "-"
```

Looks like we get 2 service addresses - `XXXXv.xxx.xx` and `XXXX.xxx.xx` - of which the one with the `XXXXv` fails. The other target then succeeds and is cached. I suspect that once the (valid) cached entry is invalidated or expires, the invalid one is tried again. That is why we're seeing the recurring behaviour.

Thanks once more for your help!
