### ISSUE TITLE
error when uploading signed cert from security server to central

### ISSUE THREAD

**Issue by Haitham-saadoon** [nordic-institute/X-Road#1554]
Hello,
I am working on the Xroad central and security containers.. I completed the installation process and no error is displayed, but 
I get an error when uploading signed.pem file to central server from security server after singing it

...
configuration_client.log reporting filenotfound exception:/etc/xroad/configuration-anchor.xml

2023-03-07T08:10:50.715Z [QuartzScheduler_Worker-3] INFO  e.r.x.c.c.g.ConfigurationClientMain$ConfigurationClientJobListener - job was execut$2023-03-07T08:11:50.714Z [QuartzScheduler_Worker-1] WARN  e.r.x.c.c.g.ConfigurationClient - Cannot download configuration, anchor file /etc/x$2023-03-07T08:11:50.714Z [QuartzScheduler_Worker-1] INFO  org.quartz.core.JobRunShell - Job jobs.ConfigurationClientJob threw a JobExecutionE$org.quartz.JobExecutionException: java.io.FileNotFoundException: /etc/xroad/configuration-anchor.xml
        at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.execute(ConfigurationClientJob.java:65)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.io.FileNotFoundException: /etc/xroad/configuration-anchor.xml
        at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.initConfigurationAnchor(ConfigurationClient.java:93)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.execute(ConfigurationClient.java:71)
        at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.execute(ConfigurationClientJob.java:51)
        ... 2 common frames omitted

regards

**Comment by Haitham-saadoon** [comment]
Hi @petkivim,
I did all the steps mentioned. but singed the request file with sign.sh not sign_req.sh .. may be this the problem.
I will retry with sign_req.sh may this solve it
thank you

**Comment by petkivim** [comment]
The easiest way to sign the certificate requests is to use the [test CA's web interface](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md#73-use-the-web-interface). It's accessible at `http://<IP_OR_DNS>:8888/testca/`.
