### ISSUE TITLE
Unexpected error writing large object to database. Server.ClientProxy.IOError: LoggingFailed.InternalError: Future timed out after [120 seconds]

### ISSUE THREAD

**Issue by Danbasik230** [nordic-institute/X-Road#1766]
Hello!
I recently got such an error related to writing to the database database. At the same time, when this error occurs, the rest of the requests stop passing. With what it can be connected? I don't understand a little. X-Road version 7.2.2.

RAM 16G
vCPU 10
Load Average cpu - 1.27
ram average - 5G

local.ini
[message-log]
keep-records-for=1
archive-interval=0 0/15 * 1/1 * ? *
clean-interval=0 0/30 * 1/1 * ? *

local.properties 
XROAD_SIGNER_PARAMS=-Xms50m -Xmx4000m
XROAD_PROXY_PARAMS=-Xms200m -Xmx8000m

This is typical errors when this error is arises.
org.apache.http.NoHttpResponseException: ss.infocom.kg:5500 failed to respond
org.apache.http.NoHttpResponseException: 185.229.37.20:5500 failed to respond
org.apache.http.NoHttpResponseException: ss-sot.tunduk.gov.kg:5500 failed to respond
org.apache.http.NoHttpResponseException: gp-ss.tunduk.gov.kg:5500 failed to respond
org.apache.http.NoHttpResponseException: 178.216.215.68:5500 failed to respond 

`2023-08-09T11:02:38.301+06:00 [Proxy-akka.control-aware-dispatcher-47] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Unexpected error writing large object to database.
2023-08-09T11:02:38.302+06:00 [qtp1484397819-5815] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (2a66b7d5-8fbd-4324-98a7-fe0fd0a94c87)
ee.ria.xroad.common.CodedException: Server.ClientProxy.IOError: LoggingFailed.InternalError: Future timed out after [120 seconds]
  at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor$ProxyMessageEntity.writeTo(ClientRestMessageProcessor.java:374)
  at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
  at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
  at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
  at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
  at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
  at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:144)
  at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:117)
  at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.sendRequest(ClientRestMessageProcessor.java:193)
  at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:174)
  at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:132)
  at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95)
  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.Server.handle(Server.java:516)
  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
  at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: ee.ria.xroad.common.CodedException: LoggingFailed.InternalError: Future timed out after [120 seconds]
  at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:232)
  at ee.ria.xroad.common.ErrorCodes.translateWithPrefix(ErrorCodes.java:247)
  at ee.ria.xroad.proxy.messagelog.MessageLog.log(MessageLog.java:123)
  
  at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor$ProxyMessageEntity.writeTo(ClientRestMessageProcessor.java:354)
  ... 36 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Future timed out after [120 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
  at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
  at scala.concurrent.Await$.result(package.scala:124)
  at scala.concurrent.Await.result(package.scala)
  at ee.ria.xroad.proxy.messagelog.MessageLog.ask(MessageLog.java:209)
  at ee.ria.xroad.proxy.messagelog.MessageLog.log(MessageLog.java:120)
  ... 37 common frames omitted
  `

**Comment by petkivim** [comment]
Hi @Danbasik230 

The error is caused by a failure in writing a request message record in the `messagelog` database. Did the error occur when you were trying to send an exceptionally big message (e.g., several gigabytes)? Are you using a local database (database running on the same host with the Security server) or a remote database (database running on an external host)? And have you checked the available disk space on the Security Server host?

Also, could you share the full proxy and signer log files (`/var/log/xroad/proxy.log`, `/var/log/xroad/signer.log`) when the error occurred?

**Comment by Danbasik230** [comment]
Hello. Database local. I think I will probably transfer the database today to a remote host. Perhaps due to the large number of requests this happens. 
[XroadSignerProxy.zip](https://github.com/nordic-institute/X-Road/files/12308643/XroadSignerProxy.zip)

**Comment by Danbasik230** [comment]
I looked at the status of the disk, for some reason I didn’t think about it all these days and it’s 95% full, sorry for asking

**Comment by Danbasik230** [comment]
I mean disk utilization*

**Comment by petkivim** [comment]
No problem! The most important thing is that the root cause was found.
