### ISSUE TITLE
Insufficient resources

### ISSUE THREAD

**Issue by hainguyen291** [nordic-institute/X-Road#26]
Hi @petkivim 

I always get this error when try to test service from ss provider.

![image](https://user-images.githubusercontent.com/12641471/45726653-5e155d80-bbea-11e8-83a9-a0b4ed21e264.png)

The error logs also appear on ss consumer concurrently.

> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:440) ~[na:1.8.0_171]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:197) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-09-19 08:57:08,119 [qtp1921553024-496] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (5682efbe-02d6-45db-ac61-e315f0a27e24)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed: Service provider did not send correct authentication certificate
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:200) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-09-19 08:57:08,120 [qtp1921553024-212-soap] ERROR e.r.x.p.c.ClientMessageProcessor - onError()
ee.ria.xroad.common.CodedException: IOError: null

My ss provider resource is:

![image](https://user-images.githubusercontent.com/12641471/45726738-bd736d80-bbea-11e8-9026-f5df6026699f.png)

.Is my ss provider really lack of resource?
Regards,
Hai

**Comment by petkivim** [comment]
Hi @hainguyen291 

Would you enable `TRACE` level logging, try sending a few messages and submit the logs here? That would help investigating the problem further.

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim 

How can I enable `TRACE` level logging?

Regards,
Hai

**Comment by petkivim** [comment]
HI @hainguyen291 

Open `/etc/xroad/conf.d/proxy-logback.xml` file for editing.

Look for this line:

`<logger name="ee.ria.xroad" level="INFO" />`

Change `level="INFO"` to `level="TRACE"`:

`<logger name="ee.ria.xroad" level="TRACE" />`

Restart proxy:

`service xroad-proxy restart`

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi @petkivim 

I have enabled `TRACE` mode. However, the performance is quite slow running on this mode. It take like 40s per request to server. 

Regards,
Hai

**Comment by petkivim** [comment]
@hainguyen291 

`TRACE` and `DEBUG` levels should be used for temporary debugging purposes only. They're not meant for permanent use. You should switch back to `INFO` level once the problem has been solved or you have collected enough log data about the problem.

Regards,
Petteri

**Comment by hainguyen291** [comment]
@petkivim 

Yeah, I know. But the problem is, I need to run such as 40CCU in 10 minutes to see the bug. It will be longer in time when `TRACE` is enabled. I will turn it `ON` once I encounter it again.

Thanks,
Hai
