### ISSUE TITLE
Problems configuring connection from a Security Server to API Rest through SSL.

### ISSUE THREAD

**Issue by alexl8a** [nordic-institute/X-Road#488]
Problems configuring connection from a firewall to API through SSL.

Hello, I already installed the infrastructure by following the X-Road Academy course.

On the other hand, I have a Rest API whose connection is through a proxy in CloudFlare, using its shared SSL certificates, created by CloudFlare itself.

Currently I managed to connect a Security Server to the API. But this connection was not secure (disable the option to validate certificates and the API address uses as HTTP protocol). I have tried several times to configure secure communication without success, and so far I have not found much documentation about it.

Has anyone done a similar configuration before? or Do you know where I can find information about it?

Regards

**Comment by petkivim** [comment]
Hi,

First, you must upload the proxy's SSL certificate to your Security Server under the subsystem that you have used to publish the REST API:

![Screenshot 2020-05-05 at 13 03 04](https://user-images.githubusercontent.com/575897/81055230-f2702900-8ed0-11ea-881a-2b570efc634d.png)

Then you must update the REST API's configuration so that `https` is used  and  `Verify TLS Certificate` option is selected:

![Screenshot 2020-05-05 at 13 02 46](https://user-images.githubusercontent.com/575897/81055237-f603b000-8ed0-11ea-8ec5-b2ef94b4c564.png)

Regards,
Petteri

**Comment by alexlopez8a** [comment]
Thanks for your answer!

As you say, I didn't have the proxy certificates registered in the subsystem. Currently I already downloaded it and followed the steps that you comment.

I also already changed the path from HTTP to HTTPS and check the box to validate TLS certificates.

Even with these changes, I still can't make a successful transaction between my client and my API.

I don't know if I'm doing something wrong. I downloaded the certificate by pressing the green padlock on the browser address bars.

I noticed that my API certificate has other nested certificates. First test by adding the direct certificate of my API, and then test by adding all (there are 3). No test was successful.


Am I skipping some other step or am I doing something wrong?

Regards

**Comment by alexl8a** [comment]
Thanks for your answer!

As you say, I didn't have the proxy certificates registered in the subsystem. Currently I already downloaded it and followed the steps that you comment.

I also already changed the path from HTTP to HTTPS and check the box to validate TLS certificates.

Even with these changes, I still can't make a successful transaction between my client and my API.

I don't know if I'm doing something wrong. I downloaded the certificate by pressing the green padlock on the browser address bars.

I noticed that my API certificate has other nested certificates. First test by adding the direct certificate of my API, and then test by adding all (there are 3). No test was successful.

Am I skipping some other step or am I doing something wrong?

Regards

**Comment by petkivim** [comment]
Hi @alexl8a 

Could you provide the error message that's returned by the consumer side Security Server when you try to invoke the API?

Could you also provide the `/var/log/xroad/proxy.log` file of the provider side Security Server that you use to publish the API?

Regards,
Petteri

**Comment by alexl8a** [comment]
Sure.

1. First, when I change de address protocol HTTP to HTTPS and I enable the validation TLS check, the system shows me the next message:
"TLS handshake with server https://api.lifechain.mx/ failed, server certificate missing from configuration"


2. This is the error message that's returned by the consumer side Security Server when I try to invoke the API:
"{
    "type": "Server.ServerProxy.IOError",
    "message": "Received fatal alert: handshake_failure",
    "detail": "ab166723-c349-4ec1-9d94-a6085f230903"
}"


3. These are the records created in "". After a failed cause on the provider side.

2020-05-07 20:39:56,987 [qtp1360878852-71] INFO  e.r.x.p.s.ServerProxyHandler - Received request from 10.173.29.190 (security server version: 6.23.0)
2020-05-07 20:39:56,987 [qtp1360878852-71] INFO  e.r.x.p.s.ServerRestMessageProcessor - process(multipart/mixed; charset=UTF-8; boundary=xtopZqIXfiWIByTKBjERfNZgGbKUcFEHmJ)


4. Finally, these are the records found on the client side.

2020-05-07 20:31:23,944 [Proxy-akka.actor.default-dispatcher-16] INFO  e.r.xroad.proxy.messagelog.TaskQueue - Start time-stamping 1 message records
2020-05-07 20:31:23,969 [Proxy-akka.actor.default-dispatcher-16] INFO  e.r.x.p.m.AbstractTimestampRequest - tsresponse org.bouncycastle.tsp.TimeStampResponse@7aec0f0f
2020-05-07 20:31:23,976 [Proxy-akka.actor.default-dispatcher-16] INFO  e.r.x.p.messagelog.TimestamperWorker - Timestamped 1 message records in 31 ms
2020-05-07 20:36:46,952 [qtp2050275256-47] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 10.173.29.1
2020-05-07 20:36:47,281 [qtp2050275256-47] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.IOError: Received fatal alert: handshake_failure
        at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:140)
        at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
        at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.checkResponse(ClientRestMessageProcessor.java:216)
        at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.parseResponse(ClientRestMessageProcessor.java:202)
        at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:165)
        at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:128)
        at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)
 


Regards.

**Comment by alexl8a** [comment]
Sure.

    First, when I change de address protocol HTTP to HTTPS and I enable the validation TLS check, the system shows me the next message:
    "TLS handshake with server https://api.****.com/ failed, server certificate missing from configuration"

    This is the error message that's returned by the consumer side Security Server when I try to invoke the API:
    "{
    "type": "Server.ServerProxy.IOError",
    "message": "Received fatal alert: handshake_failure",
    "detail": "ab166723-c349-4ec1-9d94-a6085f230903"
    }"

    These are the records created in "". After a failed cause on the provider side.

2020-05-07 20:39:56,987 [qtp1360878852-71] INFO e.r.x.p.s.ServerProxyHandler - Received request from 10.173.29.190 (security server version: 6.23.0)
2020-05-07 20:39:56,987 [qtp1360878852-71] INFO e.r.x.p.s.ServerRestMessageProcessor - process(multipart/mixed; charset=UTF-8; boundary=xtopZqIXfiWIByTKBjERfNZgGbKUcFEHmJ)

    Finally, these are the records found on the client side.

2020-05-07 20:31:23,944 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.xroad.proxy.messagelog.TaskQueue - Start time-stamping 1 message records
2020-05-07 20:31:23,969 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.x.p.m.AbstractTimestampRequest - tsresponse org.bouncycastle.tsp.TimeStampResponse@7aec0f0f
2020-05-07 20:31:23,976 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.x.p.messagelog.TimestamperWorker - Timestamped 1 message records in 31 ms
2020-05-07 20:36:46,952 [qtp2050275256-47] INFO e.r.x.p.c.AbstractClientProxyHandler - Received request from 10.173.29.1
2020-05-07 20:36:47,281 [qtp2050275256-47] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.IOError: Received fatal alert: handshake_failure
at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:140)
at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.checkResponse(ClientRestMessageProcessor.java:216)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.parseResponse(ClientRestMessageProcessor.java:202)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:165)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:128)
at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:494)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)
at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
at java.lang.Thread.run(Thread.java:748)

Regards.

**Comment by alexl8a** [comment]
Sure.

1. First, when I change de address protocol HTTP to HTTPS and I enable the validation TLS check, the system shows me the next message:
"TLS handshake with server https://api.****.com/ failed, server certificate missing from configuration"

2. This is the error message that's returned by the consumer side Security Server when I try to invoke the API:
"{
    "type": "Server.ServerProxy.IOError",
    "message": "Received fatal alert: handshake_failure",
    "detail": "ab166723-c349-4ec1-9d94-a6085f230903"
    }"


3. These are the records created in "/var/log/xroad/proxy.log". After a failed cause on the provider side.

2020-05-07 20:39:56,987 [qtp1360878852-71] INFO e.r.x.p.s.ServerProxyHandler - Received request from 10.173.29.190 (security server version: 6.23.0)
2020-05-07 20:39:56,987 [qtp1360878852-71] INFO e.r.x.p.s.ServerRestMessageProcessor - process(multipart/mixed; charset=UTF-8; boundary=xtopZqIXfiWIByTKBjERfNZgGbKUcFEHmJ)


4. Finally, these are the records found on the client side, in "/var/log/xroad/proxy.log".

2020-05-07 20:31:23,944 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.xroad.proxy.messagelog.TaskQueue - Start time-stamping 1 message records
2020-05-07 20:31:23,969 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.x.p.m.AbstractTimestampRequest - tsresponse org.bouncycastle.tsp.TimeStampResponse@7aec0f0f
2020-05-07 20:31:23,976 [Proxy-akka.actor.default-dispatcher-16] INFO e.r.x.p.messagelog.TimestamperWorker - Timestamped 1 message records in 31 ms
2020-05-07 20:36:46,952 [qtp2050275256-47] INFO e.r.x.p.c.AbstractClientProxyHandler - Received request from 10.173.29.1
2020-05-07 20:36:47,281 [qtp2050275256-47] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.IOError: Received fatal alert: handshake_failure
at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:140)
at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.checkResponse(ClientRestMessageProcessor.java:216)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.parseResponse(ClientRestMessageProcessor.java:202)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:165)
at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:128)
at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:494)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)
at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
at java.lang.Thread.run(Thread.java:748)

Regards.

**Comment by petkivim** [comment]
Thanks for the information. Based on the error message and logs the provider side Security Server still does not recognize the certificate that's provided by the API. Have you added the service using REST API base path or OpenAPI 3 description?

![Screenshot 2020-05-08 at 13 57 56](https://user-images.githubusercontent.com/575897/81399614-f5b71f00-9133-11ea-8543-7116c2aab036.png)

If you have used OpenAPI 3 description, does the `servers.url` property in your OpenAPI description point to the CloudFlare proxy? When the Security Server tries to verify the SSL certificate, it connects to the URL defined in the OpenAPI description.

```
servers:
  - url: https://api.****.com/ 
```

Regards,
Petteri

**Comment by alexl8a** [comment]
Hi Petteri,

I Used the "Rest API Base Path" option, I didn't set any property to "servers.url", I just added the API address, and assigned a service code, that was enough to achieve the communication without SSL.

Regards

**Comment by petkivim** [comment]
Hi @alexl8a,

Use of the "Rest API Base Path" option is OK, and in that case you don't need to set any additional properties. The API path that you set when you add your API is used to forward incoming requests to the API. 

Does the CloudFlare proxy listen to the standard `443` port when SSL is used? If not, you must specify the port in your API's URL. When it comes to the SSL certificates, it's enough to upload the end-user certificate issued to the proxy to the Security Server's configuration. There's no need to upload the whole certificate chain containing intermediate CA's and root CA's certificate.

For example, when `https://github.com` is added as a new service using the "Rest API Base Path" option, you must complete the steps below.

![Screenshot 2020-05-09 at 7 37 51](https://user-images.githubusercontent.com/575897/81464240-758ec900-91c8-11ea-947b-61954f3e1682.png)

![Screenshot 2020-05-09 at 7 39 47](https://user-images.githubusercontent.com/575897/81464243-7b84aa00-91c8-11ea-907e-022423d0621a.png)

![Screenshot 2020-05-09 at 7 38 06](https://user-images.githubusercontent.com/575897/81464252-850e1200-91c8-11ea-9322-5a69e16486e4.png)

![Screenshot 2020-05-09 at 7 38 20](https://user-images.githubusercontent.com/575897/81464247-80495e00-91c8-11ea-9760-4dd8edec4aa2.png)

Regards,
Petteri

**Comment by alexl8a** [comment]
Hi Petteri, 
I think I followed the steps you say

Note: For this example, use only one security server, which has 2 subsystems (one represents the client and the other the provider). I don't know if this can affect, but I am getting the same results as when I use 2 servers.

<img width="351" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31529800/81465645-0053d180-9191-11ea-9ba3-4fa9c2af7ff2.png">
<img width="355" alt="Screenshot_2" src="https://user-images.githubusercontent.com/31529800/81465719-a273b980-9191-11ea-8fec-3b8ef1ad643b.png">
<img width="401" alt="Screenshot_3" src="https://user-images.githubusercontent.com/31529800/81465758-e49cfb00-9191-11ea-85bf-57b863f0d18c.png">


If I configure the connection without verifying the TLS certificate, the communication is successful

<img width="303" alt="Screenshot_4" src="https://user-images.githubusercontent.com/31529800/81465855-d8656d80-9192-11ea-90b8-ad684eddd3d8.png">
<img width="645" alt="Screenshot_5" src="https://user-images.githubusercontent.com/31529800/81465856-e0bda880-9192-11ea-9c22-3a15575f5e21.png">


If I configure the connection with TLS certificate verification, the communication results in an error

<img width="302" alt="Screenshot_6" src="https://user-images.githubusercontent.com/31529800/81465858-e6b38980-9192-11ea-9cb5-830982622575.png">
<img width="475" alt="Screenshot_7" src="https://user-images.githubusercontent.com/31529800/81465862-e9ae7a00-9192-11ea-9fed-4e0e9857e919.png">

Regards

**Comment by petkivim** [comment]
Hi @alexl8a,

Thanks for the information. Now you have the correct certificate configured so that's not the problem anymore.

The problem seems to be that the CloudFlare proxy does not support any of the cipher suites that the Security Server supports by default. The cipher suites supported by the CloudFlare proxy seem to be:

- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- OLD_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (weak)
- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (weak)
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (weak)
- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (weak)

By default, the Security Server supports TLS 1.2 and cipher suites listed below:

- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256*
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256*
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384*
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384*
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384

(*) Not supported in RHEL when OpenJDK is used.

The solution is to update the configuration so that there's a cipher suite that's supported by both the Security Server and CloudFlare proxy. More information about changing the Security Server's configuration can be found [here](https://confluence.niis.org/pages/viewpage.action?pageId=4292898).

Regards,
Petteri

**Comment by alexl8a** [comment]
Hi Petteri,

So if I understood correctly, I should modify the file "/etc/xroad/conf.d/local.ini" and add the following content:

[proxy]
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
OLD_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384



Then I must restart the service with: service xroad-proxy restart

I followed these steps and tried again to make the request, obtaining the same result.

I went into the SSL / TLS configuration in cloudflare, and I think the certificates are also compatible with TLS 1.2.

On what you were asking about the SSL port of the proxy, I understand that it is the default (433), since I have never had the need to specify any other port to make other connections

Regards.

**Comment by petkivim** [comment]
Hi @alexl8a,

Yes, should modify the file `/etc/xroad/conf.d/local.ini` and restart the `xroad-proxy` service after that. However, your configuration is currently missing the property name ( `client-tls-ciphers`) from the beginning of the configuration:

```
[proxy]
client-tls-ciphers=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
OLD_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
```

Please note that note all the ciphers that you've listed above are supported by Java 8. The list of supported ciphers is available [here](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites).

Regards,
Petteri

**Comment by alexl8a** [comment]
Hi Petteri,
I already updated the local.ini file with the settings you shared with me.

![image](https://user-images.githubusercontent.com/31529800/81837388-6b433680-950a-11ea-9249-0c6091303bb1.png)

Then I used "service xroad-proxy restart"

Pero parece que la peticion no pasa del servidor web NGINX, supongo que tambien tengo que usar la configuracion de TLS de la misma manera.

NGINX Response:

![image](https://user-images.githubusercontent.com/31529800/81837756-e0167080-950a-11ea-85f9-8380134db9e0.png)


Regards

**Comment by petkivim** [comment]
Hi @alexl8a,

The NGINX error message is generated by the CloudFlare proxy or your service - Security Server's proxy component does not include NGINX so it cannot be the source of the error. If the CloudFlare proxy uses passthrough SSL, then your service must support the same ciphers that  are used between the Security Server and the CloudFlare proxy.

Regards,
Petteri

**Comment by petkivim** [comment]
I’m closing this issue now, but in case you require any assistance in the future, please open a new issue.
