### ISSUE TITLE
Asking help about the XRoad Read Timeout

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#526]
Dear @petkivim ,

Have you met this problems? Could you tell what is the problem?

ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.IOError: Read timed out
	at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:140)
	at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.checkResponse(ClientRestMessageProcessor.java:216)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.parseResponse(ClientRestMessageProcessor.java:202)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:165)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:128)
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:426)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:320)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:158)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Based on the error message (`Server.ServerProxy.IOError: Read timed out`) there's a problem in the connection between the provider side Security Server and the backend service. The error could be caused by various reasons, e.g., there's a firewall that's blocking the connection from the Security Server to the backend service, backend service is not running, incorrect backend service URL on the Security Server configuration.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks!

Best Regards,
Dara Penhchet
