### ISSUE TITLE
Errors during partial compilation and deployment

### ISSUE THREAD

**Issue by bthj** [nordic-institute/X-Road#564]
Hi,

when trying out the [partial compilation and deployment](https://github.com/nordic-institute/X-Road/tree/develop/ansible#partial-compilation-and-deployment) using Ansible playbooks, the process results in an error like so:
```
$ ansible-playbook -i hosts/dev-hosts.txt xroad_dev_partial.yml -e selected_modules=proxy-ui
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will 
change, but still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [lxd_servers] **********************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for 
backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for 
this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature 
will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [init-lxd : Ready all Ubuntu bionic containers] ************************************************************************************
ok: [localhost] => (item=dev-ca)
ok: [localhost] => (item=dev-ss1)
ok: [localhost] => (item=dev-ss2)
ok: [localhost] => (item=dev-cs)

TASK [init-lxd : Ready all CentOS 7 containers] *****************************************************************************************

TASK [init-lxd : Install Python2 in container if necessary] *****************************************************************************
changed: [localhost -> dev-ca] => (item=dev-ca)
changed: [localhost -> dev-ss1] => (item=dev-ss1)
changed: [localhost -> dev-ss2] => (item=dev-ss2)
changed: [localhost -> dev-cs] => (item=dev-cs)

PLAY [compile_servers] ******************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [localhost]

TASK [compile-module : Compile xroad modules proxy-ui] **********************************************************************************
failed: [localhost] (item=proxy-ui) => {"ansible_loop_var": "item", "changed": true, "cmd": ["../src/compile_module.sh", "proxy-ui", "warble"], "delta": "0:00:13.521199", "end": "2020-06-22 15:34:19.487814", "item": "proxy-ui", "msg": "non-zero return code", "rc": 1, "start": "2020-06-22 15:34:05.966615", "stderr": "rake aborted!\nBundler::GemNotFound: Could not find concurrent-ruby-1.1.5 in any of the sources\n/home/bthj/.rvm/gems/jruby-9.1.17.0@global/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in (root)'\n/home/bthj/.rvm/gems/jruby-9.1.17.0@global/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:1:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:32:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:1:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:27:in `(root)'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:1:in `(root)'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:7:in `block in (root)'\n\nCaused by:\nLoadError: no such file to load -- bundler/setup\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:32:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:1:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:27:in `<main>'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:1:in `(root)'\n/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:7:in `(root)'\n(See full trace by running task with --trace)\n\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nExecution failed for task ':proxy-ui:generateJsTranslations'.\n> Process 'command 'jruby'' finished with non-zero exit value 1\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 12s", "stderr_lines": ["rake aborted!", "Bundler::GemNotFound: Could not find concurrent-ruby-1.1.5 in any of the sources", "/home/bthj/.rvm/gems/jruby-9.1.17.0@global/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in (root)'", "/home/bthj/.rvm/gems/jruby-9.1.17.0@global/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:1:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:32:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:1:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:27:in `(root)'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:1:in `(root)'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:7:in `block in (root)'", "", "Caused by:", "LoadError: no such file to load -- bundler/setup", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/boot.rb:32:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:1:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/config/application.rb:27:in `<main>'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:1:in `(root)'", "/home/bthj/x-road-dev/X-Road/src/proxy-ui/Rakefile:7:in `(root)'", "(See full trace by running task with --trace)", "", "FAILURE: Build failed with an exception.", "", "* What went wrong:", "Execution failed for task ':proxy-ui:generateJsTranslations'.", "> Process 'command 'jruby'' finished with non-zero exit value 1", "", "* Try:", "Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.", "", "* Get more help at https://help.gradle.org", "", "BUILD FAILED in 12s"], "stdout": "Using /home/bthj/.rvm/gems/jruby-9.1.17.0\n~/x-road-dev/X-Road/src/proxy-ui ~/x-road-dev/X-Road/src\nStarting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details\n> Task :common-util:createDirs\n> Task :common-util:xjc UP-TO-DATE\n> Task :common-util:compileJava UP-TO-DATE\n> Task :common-util:make UP-TO-DATE\n> Task :common-util:processResources UP-TO-DATE\n> Task :common-util:classes UP-TO-DATE\n> Task :common-util:jar UP-TO-DATE\n> Task :common-db:compileJava UP-TO-DATE\n> Task :common-db:processResources UP-TO-DATE\n> Task :common-db:classes UP-TO-DATE\n> Task :common-db:jar UP-TO-DATE\n> Task :common-verifier:processResources UP-TO-DATE\n> Task :common-verifier:createDirs\n> Task :common-verifier:xjc UP-TO-DATE\n> Task :common-verifier:compileJava UP-TO-DATE\n> Task :common-verifier:classes UP-TO-DATE\n> Task :common-verifier:jar UP-TO-DATE\n> Task :signer-protocol:compileJava UP-TO-DATE\n> Task :signer-protocol:processResources NO-SOURCE\n> Task :signer-protocol:classes UP-TO-DATE\n> Task :signer-protocol:jar UP-TO-DATE\n> Task :common-ui:compileJava UP-TO-DATE\n> Task :common-ui:processResources NO-SOURCE\n> Task :common-ui:classes UP-TO-DATE\n> Task :common-ui:jar UP-TO-DATE\n> Task :serverconf:compileJava UP-TO-DATE\n> Task :serverconf:processResources UP-TO-DATE\n> Task :serverconf:classes UP-TO-DATE\n> Task :serverconf:jar UP-TO-DATE\n> Task :proxy-ui:compileJava UP-TO-DATE\n> Task :proxy-ui:processResources UP-TO-DATE\n> Task :proxy-ui:classes UP-TO-DATE\n> Task :proxy-ui:jar UP-TO-DATE\n> Task :proxy-ui:assemble UP-TO-DATE\n> Task :proxy-ui:checkRubySource UP-TO-DATE\n> Task :proxy-ui:checkstyleMain UP-TO-DATE\n> Task :proxy-ui:compileTestJava UP-TO-DATE\n> Task :proxy-ui:processTestResources UP-TO-DATE\n> Task :proxy-ui:testClasses UP-TO-DATE\n> Task :proxy-ui:checkstyleTest UP-TO-DATE\n> Task :proxy-ui:licenseMain UP-TO-DATE\n> Task :proxy-ui:licenseFormatLibCheck UP-TO-DATE\n> Task :proxy-ui:licenseFormatUiCheck UP-TO-DATE\n> Task :proxy-ui:licenseTest UP-TO-DATE\n> Task :proxy-ui:license UP-TO-DATE\n> Task :proxy-ui:test UP-TO-DATE\n> Task :proxy-ui:check UP-TO-DATE\n> Task :proxy-ui:copyCommon UP-TO-DATE\n> Task :proxy-ui:copyDeps UP-TO-DATE\n> Task :proxy-ui:build UP-TO-DATE\n\n> Task :proxy-ui:generateJsTranslations FAILED\n\nDeprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.\nUse '--warning-mode all' to show the individual deprecation warnings.\nSee https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings\n37 actionable tasks: 3 executed, 34 up-to-date", "stdout_lines": ["Using /home/bthj/.rvm/gems/jruby-9.1.17.0", "~/x-road-dev/X-Road/src/proxy-ui ~/x-road-dev/X-Road/src", "Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details", "> Task :common-util:createDirs", "> Task :common-util:xjc UP-TO-DATE", "> Task :common-util:compileJava UP-TO-DATE", "> Task :common-util:make UP-TO-DATE", "> Task :common-util:processResources UP-TO-DATE", "> Task :common-util:classes UP-TO-DATE", "> Task :common-util:jar UP-TO-DATE", "> Task :common-db:compileJava UP-TO-DATE", "> Task :common-db:processResources UP-TO-DATE", "> Task :common-db:classes UP-TO-DATE", "> Task :common-db:jar UP-TO-DATE", "> Task :common-verifier:processResources UP-TO-DATE", "> Task :common-verifier:createDirs", "> Task :common-verifier:xjc UP-TO-DATE", "> Task :common-verifier:compileJava UP-TO-DATE", "> Task :common-verifier:classes UP-TO-DATE", "> Task :common-verifier:jar UP-TO-DATE", "> Task :signer-protocol:compileJava UP-TO-DATE", "> Task :signer-protocol:processResources NO-SOURCE", "> Task :signer-protocol:classes UP-TO-DATE", "> Task :signer-protocol:jar UP-TO-DATE", "> Task :common-ui:compileJava UP-TO-DATE", "> Task :common-ui:processResources NO-SOURCE", "> Task :common-ui:classes UP-TO-DATE", "> Task :common-ui:jar UP-TO-DATE", "> Task :serverconf:compileJava UP-TO-DATE", "> Task :serverconf:processResources UP-TO-DATE", "> Task :serverconf:classes UP-TO-DATE", "> Task :serverconf:jar UP-TO-DATE", "> Task :proxy-ui:compileJava UP-TO-DATE", "> Task :proxy-ui:processResources UP-TO-DATE", "> Task :proxy-ui:classes UP-TO-DATE", "> Task :proxy-ui:jar UP-TO-DATE", "> Task :proxy-ui:assemble UP-TO-DATE", "> Task :proxy-ui:checkRubySource UP-TO-DATE", "> Task :proxy-ui:checkstyleMain UP-TO-DATE", "> Task :proxy-ui:compileTestJava UP-TO-DATE", "> Task :proxy-ui:processTestResources UP-TO-DATE", "> Task :proxy-ui:testClasses UP-TO-DATE", "> Task :proxy-ui:checkstyleTest UP-TO-DATE", "> Task :proxy-ui:licenseMain UP-TO-DATE", "> Task :proxy-ui:licenseFormatLibCheck UP-TO-DATE", "> Task :proxy-ui:licenseFormatUiCheck UP-TO-DATE", "> Task :proxy-ui:licenseTest UP-TO-DATE", "> Task :proxy-ui:license UP-TO-DATE", "> Task :proxy-ui:test UP-TO-DATE", "> Task :proxy-ui:check UP-TO-DATE", "> Task :proxy-ui:copyCommon UP-TO-DATE", "> Task :proxy-ui:copyDeps UP-TO-DATE", "> Task :proxy-ui:build UP-TO-DATE", "", "> Task :proxy-ui:generateJsTranslations FAILED", "", "Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.", "Use '--warning-mode all' to show the individual deprecation warnings.", "See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings", "37 actionable tasks: 3 executed, 34 up-to-date"]}

PLAY RECAP ******************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

```

This is on Ubuntu 18.04.4 LTS where the scripts `./prepare_buildhost.sh` and `./update_ruby_dependencies.sh` have been run, according to the [dependency installation and building instructions](https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md#dependency-installation-and-building-instructions).

Is it like it seems, a Gradle version issue?

**Comment by petkivim** [comment]
Hi @bthj 

It seems like a jruby installation/dependency issue. You seem to have bundler 2.1.4 installed, but it should be version 1.14.6.

Regards,
Petteri

**Comment by bthj** [comment]
Thanks.  I had installed jruby separately before.  When trying this on a new (virtual) machine, the partial compilation and deployment runs without error.

The command `ansible-playbook  -i hosts/lxd_hosts.txt xroad_dev.yml`, issued when following the steps towards the end of [4. Development using Ansible playbooks](https://github.com/nordic-institute/X-Road/tree/develop/ansible#4-development-using-ansible-playbooks), does fail on that fresh Ubuntu 18 machine, but that's not what is being reported here, so I'll close this issue.
