### ISSUE TITLE
Asking about Nginx port 8090

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road#567]
Dear @petkivim ,

For XRoad Security Server in Redhat, the Nginx Service is running with port 4000 and 8090 right? And what is the purpose of port 8090?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

On both Ubuntu and Red Hat Nginx is running in port 4000. Port 8090 is not used by the Security Server.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your answer.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question related to Security Server Connection ? What is the problems?

`{
    "type" : "Server.ServerProxy.InternalError",
    "message" : "Connection pool shut down",
    "detail" : "21d2a54c-c946-496c-bffa-f845d91c5ac4"
  }`

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The error is generated by the provider side Security Server. Have you checked the `/var/log/xroad/proxy.log` for details?

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

`ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.InternalError: Connection pool shut down
	at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:140)
	at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.checkResponse(ClientRestMessageProcessor.java:216)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.parseResponse(ClientRestMessageProcessor.java:202)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.processRequest(ClientRestMessageProcessor.java:165)
	at ee.ria.xroad.proxy.clientproxy.ClientRestMessageProcessor.process(ClientRestMessageProcessor.java:128)
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)`

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Thanks for the information. Unfortunately, it does not provide enough information to be able to say what's causing the problem. Have you tried to restart `xroad-proxy` service on the provider side Security Server and see if that helps? Another way to debug the problem further is to enable more detailed logging on the provider side Security Server:

https://confluence.niis.org/pages/viewpage.action?pageId=6783404

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,
 
One more question could you help to check this error?

`ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.InternalError: connect timed out`

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

This time, the error is generated by the consumer side Security Server. The error indicates that the consumer side Security Server is not able to establish a network connection to the provider side Security Server. Typically this is caused by incorrect firewall configurations on the provider side.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your reply.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Could I ask you one more question related to this error?

`2020-07-07 13:53:12,344 [qtp773238925-26311] ERROR e.r.x.p.c.AuthTrustVerifier - Error while getting peer certificates
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated`

`ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed: Service provider did not send correct authentication certificate`

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The error seems to be generated by the consumer side Security Server. It means that there's a problem with the authentication certificate of the provider side Security Server. Please check the configuration of the provider side Security Server and make sure that it has a valid authentication certificate.

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks for your reply.

Could I ask you one more question related to the register the authenticate certificate on security server?

![image](https://user-images.githubusercontent.com/8038324/86761413-24883d80-c070-11ea-9239-51e20f99c0b1.png)

Best Regards, 
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

The authentication certificate registration request is sent to the Central Server port 4001. Have you checked that it's accessible from the Security Server?

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

Thanks I will check that connection.

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @petkivim ,

it cannot connect to Central Server with port 4001 successfully, but it will show the same error message. Could you help to check it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Thanks for the clarification. In that case, please look for additional details from the `/var/log/xroad/jetty/jetty.log` log file on the Security Server.

If you test the connection using telnet, you get the same result?

```
$ telnet <central-server-host> 4001

Trying x.x.x.x...
Connected to <central-server-host>.
Escape character is '^]'.
```

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

it still shows the same error. and the connection to Central server is working well.

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi @darapenhchet 

Here's some ideas what to check next:

* Have you checked the logs?
* Have you  also checked that the central services are running normally?
* Are you able to send management requests from other Security Servers?
* If you have a Central Server cluster, have you checked that all the nodes of the cluster are accessible from the Security Server?

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear @petkivim ,

I have checked the logs already and Central Services are running normally. I think the problems maybe come from the firewall of our services. And we will try to check it.

Thanks for your ideas.

Best Regards,
Dara Penhchet
