### ISSUE TITLE
Ploblem with install CS version 6.23.0

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#569]
I have a problem with CS version 6.23.0. When I complete the installation, I login to CS admin and config but CS has error "Global configuration generation failing since....."

- I check on configuration_client.log file and have error:
2020-06-26 14:57:57,833 [Thread-0] INFO e.r.x.c.c.g.ConfigurationClientMain - Configuration client shutting down...
2020-06-26 14:57:57,833 [Thread-0] INFO org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED shutting down.
2020-06-26 14:57:57,833 [Thread-0] INFO org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED paused.
2020-06-26 14:57:57,834 [Thread-0] INFO org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED shutdown complete.
2020-06-26 14:57:57,841 [Thread-0] INFO o.e.jetty.server.AbstractConnector - Stopped AdminPort@4516af24{HTTP/1.1,[http/1.1]}{127.0.0.1:5675}
2020-06-26 14:57:58,200 [main] INFO org.eclipse.jetty.util.log - Logging initialized @327ms to org.eclipse.jetty.util.log.Slf4jLog
2020-06-26 14:57:58,229 [main] INFO ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5675
2020-06-26 14:57:58,231 [main] INFO org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_252-8u252-b09-1~18.04-b09
2020-06-26 14:57:58,260 [main] INFO o.e.jetty.server.AbstractConnector - Started AdminPort@4516af24{HTTP/1.1,[http/1.1]}{127.0.0.1:5675}
2020-06-26 14:57:58,260 [main] INFO org.eclipse.jetty.server.Server - Started @390ms
2020-06-26 14:57:58,298 [main] INFO org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2020-06-26 14:57:58,308 [main] INFO o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2020-06-26 14:57:58,308 [main] INFO org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.2 created.
2020-06-26 14:57:58,308 [main] INFO org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2020-06-26 14:57:58,309 [main] INFO org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
NOT STARTED.
Currently in standby mode.
Number of jobs executed: 0
Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2020-06-26 14:57:58,309 [main] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'QuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2020-06-26 14:57:58,309 [main] INFO org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
2020-06-26 14:57:58,314 [main] INFO org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2020-06-26 14:57:58,314 [main] INFO e.r.x.c.c.g.ConfigurationClientMain - Configuration client started
2020-06-26 14:57:58,623 [QuartzScheduler_Worker-1] INFO e.r.x.c.c.g.ConfigurationDownloader - Downloading configuration from http://cs01.cmsc.gov.vn/internalconf?version=2
2020-06-26 14:57:58,637 [QuartzScheduler_Worker-1] ERROR e.r.x.c.c.g.ConfigurationClient - Failed to download configuration from any configuration location:
location: http://cs01.cmsc.gov.vn/internalconf?version=2; error: HttpError: http://cs01.cmsc.gov.vn/internalconf?version=2

2020-06-26 14:57:58,639 [QuartzScheduler_Worker-1] INFO org.quartz.core.JobRunShell - Job jobs.ConfigurationClientJob threw a JobExecutionException:
org.quartz.JobExecutionException: HttpError: http://cs01.cmsc.gov.vn/internalconf?version=2
at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.execute(ConfigurationClientJob.java:61)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: ee.ria.xroad.common.CodedException: HttpError: http://cs01.cmsc.gov.vn/internalconf?version=2
at ee.ria.xroad.common.conf.globalconf.ConfigurationLocation.getInputStream(ConfigurationLocation.java:73)
at ee.ria.xroad.common.conf.globalconf.ConfigurationParser.getInputStream(ConfigurationParser.java:127)
at ee.ria.xroad.common.conf.globalconf.ConfigurationParser.parse(ConfigurationParser.java:117)
at ee.ria.xroad.common.conf.globalconf.ConfigurationDownloader.download(ConfigurationDownloader.java:167)
at ee.ria.xroad.common.conf.globalconf.ConfigurationDownloader.download(ConfigurationDownloader.java:115)
at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.downloadConfigurationFromAnchor(ConfigurationClient.java:140)
at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.execute(ConfigurationClient.java:72)
at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.execute(ConfigurationClientJob.java:50)
... 2 common frames omitted
Caused by: java.io.FileNotFoundException: http://cs01.cmsc.gov.vn/internalconf?version=2
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
at ee.ria.xroad.common.conf.globalconf.ConfigurationLocation.getInputStream(ConfigurationLocation.java:71)
... 9 common frames omitted
2020-06-26 14:57:58,640 [QuartzScheduler_Worker-1] INFO e.r.x.c.c.g.ConfigurationClientMain$ConfigurationClientJobListener - job was executed result=DiagnosticsStatus(returnCode=122, prevUpdate=14:57:58.638, nextUpdate=14:58:58.638, description=null)

- I try to call by command: curl http://cs01.cmsc.gov.vn/internalconf?version=2 and get error:

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

- status of xroad-confclient is OK. Please, give me a solution for this. Thanks.

**Comment by petkivim** [comment]
Hi @trungnv0412 

Have you completed the configuration steps described here:

https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-1.ConfigurationoftheCentralServer

Regards,
Petteri

**Comment by trungnv0412** [comment]
Dear @petkivim!

I try it and my ploblem was fix. Thank you very much!

**Comment by petkivim** [comment]
That's good to hear. You're welcome!
