### ISSUE TITLE
How to config LoadBalancing for security server?

### ISSUE THREAD

**Issue by nguyenhabkit** [nordic-institute/X-Road#72]
Hi @petkivim, it's me again!
Thank you so much for your supports before! and now I need your help about this:
I installed Loadbalancing for 2 Security server (named A, B) successfully following this guide:https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md#3-x-road-installation-and-configuration
After that, I registry the SS A to a member of Center server ok, its was synchronized all configuration of SS A  to SS B
Now, I config a LoadBalance server  for 2 SS A and B, then change IP of SS in Security Server details in Center server admin interface by Loadbalancing's IP look like this:
![screenshot_6](https://user-images.githubusercontent.com/37961023/50201229-d4616180-038b-11e9-8e6f-f0ccb9232ecf.png)
But, The LoadBalancing does not work!
I don't know what's wrong in my config, I don't find out any document about config LB. Please tell me how to config it?
Thanks.
Ha.

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

You're welcome.

Once you have set up your Security Server cluster, you must register the Security Servers to your LB as targets so that the LB routes traffic to the Security Servers. How the registration is done, depends on the LB that you're using. Unfortunately, I cannot provide support regarding configuration of different LBs. Please consult the LBs documentation and/or community for instructions.

Once the LB is routing traffic to the Security Servers, you should change the IP/DNS of the Security Server master node to the IP/DNS of the LB on Central Server. Within few minutes the change propagates to other Security Servers within your X-Road instance.

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Hi @petkivim ,
I'm using nginx to config the LB, here is my configuration:
upstream ss_80 {
    server 10.0.14.234:80;
    server 10.0.14.233:80;
    ip_hash;
}

server {
        listen 80;
        error_log /var/log/nginx/ssprovider_error.log error;
	access_log  /var/log/nginx/ssprovider_access.log;
	location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;
               proxy_pass http://ss_80;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

upstream ss_443 {
    server 10.0.14.234:443;
    server 10.0.14.233:443;
    ip_hash;
}

server {
        listen 443;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;
               proxy_pass http://ss_443;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

upstream ss_5500 {
    server 10.0.14.234:5500;
    server 10.0.14.233:5500;
    ip_hash;
}

server {
        listen 5500;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;                                                                                                                                       
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;                                                                                                                                                        
               proxy_send_timeout 5m;
               proxy_pass https://ss_5500;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

upstream ss_5577 {
    server 10.0.14.234:5577;
    server 10.0.14.233:5577;
    ip_hash;
}

server {
        listen 5577;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                                                                                                
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;                                                                                                                                                        
               proxy_pass https://ss_5577;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}
upstream ss_4001 {
    server 10.0.14.234:4001;
    server 10.0.14.233:4001;
    ip_hash;
}

server {
        listen 4001;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                                                                                                
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;                                                                                                                                                        
               proxy_pass https://ss_4001;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

Please have a look,
In that 10.0.14.234, and  10.0.14.233  are IPs of 2 SS node.
On 2 these SS I provide a service. after that I use a SS comsumer to test this service, it show this error in proxy log of SS consumer like this:
2018-12-19 17:32:15,499 [qtp489070295-58] ERROR e.r.x.p.c.AuthTrustVerifier - Error while getting peer certificates
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:440) ~[na:1.8.0_171]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:197) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) [proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) [proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) [proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) [proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) [proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-12-19 17:32:15,503 [qtp489070295-58] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (a8be4c30-a575-4f53-8e56-b4ea7681187d)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed: Service provider did not send correct authentication certificate
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getPeerCertificates(AuthTrustVerifier.java:200) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:82) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]

**Comment by petkivim** [comment]
I'm not an expert in Nginx configuration so I don't comment the configuration details.
                                      
When it comes to X-Road specific configuration, only ports `5500` and `5577` of the provider side Security Servers should go through the LB. You can remove ports `80`, `443` and `4001` from the configuration. In addition, try changing the line `proxy_pass https://ss_5577;` to `proxy_pass http://ss_5577;`.

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Thanks @petkivim ,
I will change the configuration as you guide.

**Comment by nguyenhabkit** [comment]
Hi @petkivim ,
On the answers above you said that: "Once the LB is routing traffic to the Security Servers, you should change the IP/DNS of the Security Server master node to the IP/DNS of the LB on Central Server."
So, I change it on Central server like photo below is correct or not?
![screenshot_6](https://user-images.githubusercontent.com/37961023/50437693-739ecf80-091d-11e9-963f-5e37fbd27964.png)
Or if changing need to do on somewhere else. Please let me know!

Thanks,
Ha.

**Comment by petkivim** [comment]
Hi @nguyenhabkit,

Yes, that's the right place. 

Regards, 
Petteri

**Comment by nguyenhabkit** [comment]
@petkivim ,
There are steps that I config LB for 2 SS Provider:
1. The configuration file of LB looks like this: IP of LB is 10.0.14.237 
upstream ss_5500 {
   ip_hash;
   server 10.0.14.233:5500;
   server 10.0.14.234:5500;
}
server {
        listen 5500;
	server_name _ lienthong.vpcp.vn;
	ssl on;
	ssl_certificate /etc/nginx/ssl/lienthongvpcpfullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkeylienthongvpcp.pem;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;                                                                                                                                       
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;                                                                                                                                                        
               proxy_send_timeout 5m;
               proxy_pass https://ss_5500;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

upstream ss_5577 {
   ip_hash;
    server 10.0.14.233:5577;
    server 10.0.14.234:5577;
}
server {
        listen 5577;
        error_log /var/log/nginx/ssprovider_error.log error;
        access_log  /var/log/nginx/ssprovider_access.log;
        location / {
               proxy_set_header X-Forwarded-Host $host;
               proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;                                                                                                                
               proxy_set_header Host $http_host;
               proxy_read_timeout 5m;
               proxy_send_timeout 5m;                                                                                                                                                        
               proxy_pass http://ss_5577;

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
}

2. Use ip of LB server to registry auth cert SS provider 
![image](https://user-images.githubusercontent.com/37961023/50477497-39a5fa00-09ff-11e9-95a8-4963bd413cf6.png)

3. After resgistrying SS provider successfully. I registry a provider client on it -> this is OK
4.  Using another SS to be a SS consumer, I registry a consumer client on it to call services of SS provider. But It can not be done and show this error on proxy log like this:
2018-12-27 15:01:04,897 [qtp68217166-98] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (2a3aa8cb-f9a0-42fa-823b-cae401b48f77)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.CannotCreateCertPath.InternalError: Certificate is not issued by approved certification service provider.
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.lambda$getCaCert$5(GlobalConfImpl.java:342) ~[proxy-1.0.jar:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_171]
	at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.getCaCert(GlobalConfImpl.java:341) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.conf.globalconf.GlobalConf.getCaCert(GlobalConf.java:369) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.cert.CertChain.create(CertChain.java:102) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verifyAuthCert(AuthTrustVerifier.java:104) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:89) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:194) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:148) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:297) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:238) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
2018-12-27 15:01:04,897 [qtp68217166-98-soap] ERROR e.r.x.p.c.ClientMessageProcessor - onError()
ee.ria.xroad.common.CodedException: IOError: null
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:205) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:120) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.writeOcspResponses(ClientMessageProcessor.java:701) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.soap(ClientMessageProcessor.java:633) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.readSoapMessage(SoapMessageDecoder.java:165) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapMessageDecoder.parse(SoapMessageDecoder.java:132) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.handleSoap(ClientMessageProcessor.java:596) [proxy-1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.io.InterruptedIOException: null
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:275) ~[na:1.8.0_171]
	at java.io.PipedInputStream.receive(PipedInputStream.java:231) ~[na:1.8.0_171]
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_171]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_171]
	at ee.ria.xroad.common.util.MultipartEncoder.write(MultipartEncoder.java:184) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:118) ~[proxy-1.0.jar:na]

I don't know how to fix it, Please see the log and let me know what wrong I am?

Thanks,
Ha.

**Comment by petkivim** [comment]
Hi @nguyenhabkit,

You must use SSL passthrough on Nginx -  it sends SSL connections directly to the Security Servers. Doing SSL termination on Nginx would generate `Server.ClientProxy.SslAuthenticationFailed.CannotCreateCertPath.InternalError: Certificate is not issued by approved certification service provider` error. Please consult the Nginx documentation regarding the correct configuration.

Regards,
Petteri

**Comment by nguyenhabkit** [comment]
Hi @petkivim ,
Thank you so much for your information!

**Comment by nguyenhabkit** [comment]
Hi @petkivim ,
Sorry for a long time no discussion, I have work off for new year holiday.
And I'm glad to tell you that the problem was resolved by using passthrough on Nginx.
Thank you and Happy new year!

Best regards,
Ha

**Comment by petkivim** [comment]
Hi @nguyenhabkit 

Good to hear that the problem was resolved.

Happy New Year!

Regards,
Petteri
