### ISSUE TITLE
Error while building 6.19.0 deb

### ISSUE THREAD

**Issue by kmpsaravanan** [nordic-institute/X-Road#78]
Dear Petteri, Andres,
 
while trying to build 6.19.0 deb files, got an error (please refer the attachment).
 
[standard output.txt](https://github.com/nordic-institute/X-Road/files/2712316/standard.output.txt)

As per the attached output, the test script is looking for this script in /usr/share/xroad/scripts/validate-test-configuration-part.sh. But unable to find this script in the NIIS repo, github repo.
 
Kindly guide. Thank you in advance.
 
Regards,
Saro
 
./build_packages.sh
Warning! PATH is not properly set up, /usr/share/rvm/gems/ruby-2.5.3/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-2.5.3
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
Using /usr/share/rvm/gems/jruby-9.1.13.0
Starting a Gradle Daemon (subsequent builds will be faster)
 
> Task :center-service:warble
rm -f build/libs/center-service.war
Creating build/libs/center-service.war
 
> Task :center-ui:warble
rm -f build/libs/center-ui.war
Creating build/libs/center-ui.war
 
> Task :proxy-ui:warble
rm -f build/libs/proxy-ui.war
Creating build/libs/proxy-ui.war
 
> Task :common-ui:test
 
ee.ria.xroad.commonui.OptionalPartsConfBehavior > shouldAddErrorsIfCannotReadConfigurationPartFile FAILED
    java.lang.AssertionError at OptionalPartsConfBehavior.java:132
 
13 tests completed, 1 failed
 
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':common-ui:test'.
> There were failing tests. See the report at: file:///xroad/X-Road/src/common-ui/build/reports/tests/test/index.html
 
* Try:
Run with --info or --debug option to get more log output.
 
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':common-ui:test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///xroad/X-Road/src/common-ui/build/reports/tests/test/index.html
        at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1438)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:712)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
 
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 1m 6s
142 actionable tasks: 10 executed, 132 up-to-date

**Comment by petkivim** [comment]
Hi @kmpsaravanan 

Unfortunately, we are not able to reproduce the problem on a clean build host.

`validate-test-configuration-part.sh` does not exist, it is part of some test configuration data used to verify that reading the configuration works. It seems that the failure is not even related to that - the build fails on:

> ee.ria.xroad.commonui.OptionalPartsConfBehavior > shouldAddErrorsIfCannotReadConfigurationPartFile FAILED
> java.lang.AssertionError at OptionalPartsConfBehavior.java:132

Regards,
Petteri

**Comment by kmpsaravanan** [comment]
Hi Petteri, Good morning. While compiling the xroad code (cloned from NIIS github repo), getting error in passwordstore test. The build is failing at TASK common-util:test at ee.ria.xroad.common.util.PasswordStoreTest > runTest FAILED
   java.lang.RuntimeException at PasswordStoreTest.java:45
anyone have faced this error or what can be the action to be taken
I am compiling the code in Ubuntu 14.04 VM

Regards,
Saro

**Comment by petkivim** [comment]
Hi @kmpsaravanan 

Have you followed the instructions for building X-Road, and completed all the required steps before trying to build the packages?

https://github.com/nordic-institute/X-Road/blob/0c28dbc8d99a8c5e7ce30d68517813b058b48a9f/src/BUILD.md

Regards,
Petteri

**Comment by petkivim** [comment]
This X-Road Knowledge Base article should help you with the problem:

https://confluence.niis.org/pages/viewpage.action?pageId=8521867

Regards,
Petteri
