### ISSUE TITLE
Problem when tranfer file > 160MB

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#835]
Dear @petkivim!

I have a poloblem when send a file > 160 MB beetwen 2 servers SS. Error in proxy.log:

2021-01-14 18:44:44,142 [qtp1668385683-1663] ERROR e.r.x.p.s.ServerProxyHandler - Request processing error (1957203a-779c-4e06-9392-c63e3a6beae3)
ee.ria.xroad.common.CodedException: Server.ServerProxy.ServiceFailed.IOError: Read timed out
	at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:205) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor.sendRequest(ServerMessageProcessor.java:440) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor.access$1300(ServerMessageProcessor.java:86) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor$DefaultServiceHandlerImpl.startHandling(ServerMessageProcessor.java:610) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor.handleRequest(ServerMessageProcessor.java:228) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor.process(ServerMessageProcessor.java:130) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerProxyHandler.handle(ServerProxyHandler.java:90) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:258) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:147) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_171]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_171]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[proxy-1.0.jar:na]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[proxy-1.0.jar:na]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[proxy-1.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:115) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:95) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.serverproxy.ServerMessageProcessor.sendRequest(ServerMessageProcessor.java:432) ~[proxy-1.0.jar:na]
	... 19 common frames omitted
2021-01-14 18:44:44,162 [qtp465233746-132] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.ServiceFailed.IOError: Read timed out
	at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:138) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:127) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.checkResponse(ClientMessageProcessor.java:389) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.parseResponse(ClientMessageProcessor.java:355) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:244) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:203) ~[proxy-1.0.jar:na]
	at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:95) ~[proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:564) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [proxy-1.0.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [proxy-1.0.jar:na]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672) [proxy-1.0.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590) [proxy-1.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

Can you support me this error?

Thanks, Trungnv.

**Comment by petkivim** [comment]
Hi @trungnv0412 

Have you checked the logs of the service receiving the message? Based on the error code (`Server.ServerProxy.ServiceFailed.IOError`) the service failed process the request.

Regards,
Petteri

**Comment by trungnv0412** [comment]
Thank for your support, i fixed it.

Thanks, Trungnv.
