### ISSUE TITLE
SS not work.

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#898]
Dear @petkivim !

**_- When i start xroad-proxy, i have logs below:_**

2021-02-26 16:56:34,114 [Thread-3] INFO  ee.ria.xroad.proxy.ProxyMain - Proxy shutting down...
2021-02-26 16:56:34,114 [Thread-3] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED shutting down.
2021-02-26 16:56:34,114 [Thread-3] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED paused.
2021-02-26 16:56:34,115 [Thread-3] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED shutdown complete.
2021-02-26 16:56:34,124 [Thread-3] INFO  o.e.jetty.server.AbstractConnector - Stopped ClientConnector@69ce2f62{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2021-02-26 16:56:34,125 [Thread-3] INFO  o.e.jetty.server.AbstractConnector - Stopped ClientSSLConnector@2e3a5237{SSL,[ssl, http/1.1]}{0.0.0.0:443}
2021-02-26 16:56:34,129 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Close initiated...
2021-02-26 16:56:34,136 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Closed.
2021-02-26 16:56:34,138 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Close initiated...
2021-02-26 16:56:34,163 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Closed.
2021-02-26 16:56:34,166 [Thread-3] INFO  o.e.jetty.server.AbstractConnector - Stopped ClientProxyConnector@6b1e7ad3{SSL,[ssl, http/1.1]}{0.0.0.0:5500}
2021-02-26 16:56:45,049 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.e.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
2021-02-26 16:56:45,050 [Proxy-akka.actor.default-dispatcher-4] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-3 - Started.
2021-02-26 16:56:45,064 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: ee.ria.xroad.common.db.CustomPostgreSQLDialect
2021-02-26 16:56:45,111 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.e.j.e.i.LobCreatorBuilderImpl - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2021-02-26 16:56:45,112 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.type.BasicTypeRegistry - HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@925ae60
2021-02-26 16:56:45,183 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.h.i.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory
2021-02-26 16:56:49,168 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Close initiated...
2021-02-26 16:56:49,178 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Closed.
2021-02-26 16:56:49,179 [Thread-3] INFO  o.e.jetty.server.AbstractConnector - Stopped OcspResponseConnector@7a18e8d{HTTP/1.1,[http/1.1]}{0.0.0.0:5577}
2021-02-26 16:56:49,181 [Thread-3] INFO  o.e.jetty.server.AbstractConnector - Stopped AdminPort@3bcd426c{HTTP/1.1,[http/1.1]}{127.0.0.1:5566}
2021-02-26 16:56:49,189 [Proxy-akka.actor.default-dispatcher-14] INFO  e.r.x.proxy.messagelog.LogManager - cancelNextTick called, cancel() return value: true
2021-02-26 16:56:50,248 [Proxy-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2021-02-26 16:56:50,429 [main] INFO  ee.ria.xroad.proxy.ProxyMain - Starting proxy (6.23.0)...
2021-02-26 16:56:51,079 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2021-02-26 16:56:51,093 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-02-26 16:56:51,093 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.2 created.
2021-02-26 16:56:51,094 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2021-02-26 16:56:51,095 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-02-26 16:56:51,095 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'QuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2021-02-26 16:56:51,095 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
2021-02-26 16:56:51,109 [main] WARN  e.r.xroad.proxymonitor.ProxyMonitor - Could not load configuration property xroad.monitor.port - using the default port
2021-02-26 16:56:51,126 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1846ms to org.eclipse.jetty.util.log.Slf4jLog
2021-02-26 16:56:51,149 [main] INFO  org.eclipse.jetty.util.TypeUtil - JVM Runtime does not support Modules
2021-02-26 16:56:51,295 [main] WARN  o.e.jetty.server.AbstractConnector - Ignoring deprecated socket close linger time
2021-02-26 16:56:51,296 [main] INFO  e.r.x.proxy.clientproxy.ClientProxy - Client HTTP connector created (0.0.0.0:80)
2021-02-26 16:56:51,302 [main] INFO  e.r.x.proxy.clientproxy.ClientProxy - Client HTTPS connector created (0.0.0.0:443)
2021-02-26 16:56:51,393 [main] INFO  e.r.x.p.s.HttpClientCreator - SSL context successfully created
2021-02-26 16:56:51,408 [main] INFO  e.r.x.proxy.serverproxy.ServerProxy - ClientProxy AntiDosConnector created (0.0.0.0:5500)
2021-02-26 16:56:51,417 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2021-02-26 16:56:51,418 [main] INFO  ee.ria.xroad.proxy.ProxyMain - JobManager started
2021-02-26 16:56:51,419 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
2021-02-26 16:56:51,452 [main] INFO  o.e.jetty.server.AbstractConnector - Started ClientConnector@69ce2f62{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2021-02-26 16:56:51,468 [main] INFO  o.e.jetty.server.AbstractConnector - Started ClientSSLConnector@2e3a5237{SSL,[ssl, http/1.1]}{0.0.0.0:443}
2021-02-26 16:56:51,468 [main] INFO  org.eclipse.jetty.server.Server - Started @2188ms
2021-02-26 16:56:51,468 [main] INFO  ee.ria.xroad.proxy.ProxyMain - ClientProxy started
2021-02-26 16:56:51,468 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
2021-02-26 16:56:51,479 [main] INFO  o.e.jetty.server.AbstractConnector - Started ClientProxyConnector@6b1e7ad3{SSL,[ssl, http/1.1]}{0.0.0.0:5500}
2021-02-26 16:56:51,486 [main] INFO  org.eclipse.jetty.server.Server - Started @2205ms
2021-02-26 16:56:51,486 [main] INFO  ee.ria.xroad.proxy.ProxyMain - ServerProxy started
2021-02-26 16:56:51,486 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
2021-02-26 16:56:51,497 [main] INFO  o.e.jetty.server.AbstractConnector - Started OcspResponseConnector@7a18e8d{HTTP/1.1,[http/1.1]}{0.0.0.0:5577}
2021-02-26 16:56:51,498 [main] INFO  org.eclipse.jetty.server.Server - Started @2217ms
2021-02-26 16:56:51,498 [main] INFO  ee.ria.xroad.proxy.ProxyMain - CertHashBasedOcspResponder started
2021-02-26 16:56:51,498 [main] INFO  ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5566
2021-02-26 16:56:51,498 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
2021-02-26 16:56:51,501 [main] INFO  o.e.jetty.server.AbstractConnector - Started AdminPort@3bcd426c{HTTP/1.1,[http/1.1]}{127.0.0.1:5566}
2021-02-26 16:56:51,502 [main] INFO  org.eclipse.jetty.server.Server - Started @2221ms
2021-02-26 16:56:51,502 [main] INFO  ee.ria.xroad.proxy.ProxyMain - AdminPort started
2021-02-26 16:56:52,221 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.Version - HHH000412: Hibernate Core {[WORKING]}
2021-02-26 16:56:52,222 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
2021-02-26 16:56:52,626 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2021-02-26 16:56:53,356 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.e.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
2021-02-26 16:56:53,368 [Proxy-akka.actor.default-dispatcher-4] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
2021-02-26 16:56:53,468 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: ee.ria.xroad.common.db.CustomPostgreSQLDialect
2021-02-26 16:56:53,546 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.e.j.e.i.LobCreatorBuilderImpl - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2021-02-26 16:56:53,554 [Proxy-akka.actor.default-dispatcher-4] INFO  org.hibernate.type.BasicTypeRegistry - HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@24133127
2021-02-26 16:56:54,233 [Proxy-akka.actor.default-dispatcher-4] INFO  o.h.h.i.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory

**_- When I start xroad-signer, i have logs below:_**

2021-02-26 16:56:49,210 ERROR [Signer-akka.actor.default-dispatcher-27] akka.remote.EndpointWriter - AssociationError [akka.tcp://Signer@127.0.0.1:5558] <- [akka.tcp://Proxy@127.0.0.1:5567]: Error [Shut down address: akka.tcp://Proxy@127.0.0.1:5567] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://Proxy@127.0.0.1:5567
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
]
2021-02-26 16:56:56,722 INFO  [Thread-0] ee.ria.xroad.signer.SignerMain - Signer shutting down...
2021-02-26 16:56:56,800 INFO  [Thread-0] o.e.jetty.server.AbstractConnector - Stopped AdminPort@376b4233{HTTP/1.1,[http/1.1]}{127.0.0.1:5559}
2021-02-26 16:56:56,842 INFO  [main] ee.ria.xroad.signer.SignerMain - Signer shutting down...
2021-02-26 16:56:57,451 INFO  [main] ee.ria.xroad.signer.SignerMain - Starting Signer on port 5558...
2021-02-26 16:56:57,472 INFO  [main] org.eclipse.jetty.util.log - Logging initialized @597ms to org.eclipse.jetty.util.log.Slf4jLog
2021-02-26 16:56:58,113 INFO  [Signer-akka.actor.default-dispatcher-3] akka.event.slf4j.Slf4jLogger - Slf4jLogger started
2021-02-26 16:56:58,376 INFO  [main] ee.ria.xroad.common.util.AdminPort - Started AdminPort on port 5559
2021-02-26 16:56:58,380 INFO  [main] org.eclipse.jetty.server.Server - jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
2021-02-26 16:56:58,415 INFO  [main] o.e.jetty.server.AbstractConnector - Started AdminPort@376b4233{HTTP/1.1,[http/1.1]}{127.0.0.1:5559}
2021-02-26 16:56:58,416 INFO  [main] org.eclipse.jetty.server.Server - Started @1542ms
2021-02-26 16:57:03,867 INFO  [Signer-akka.actor.default-dispatcher-15] e.r.x.s.certmanager.OcspClientWorker - OCSP-response refresh cycle started
2021-02-26 16:57:03,867 INFO  [Signer-akka.actor.default-dispatcher-4] ee.ria.xroad.signer.OcspClientJob - Next OCSP refresh scheduled in 1200 seconds
2021-02-26 16:57:03,901 INFO  [Signer-akka.actor.default-dispatcher-15] e.r.x.s.certmanager.OcspClientWorker - Fetching OCSP responses for 3 certificates
2021-02-26 16:57:04,041 INFO  [Signer-akka.actor.default-dispatcher-4] ee.ria.xroad.signer.OcspClientJob - OCSP-response refresh cycle successfully completed, continuing with normal scheduling
2021-02-26 16:57:11,266 **ERROR [Signer-akka.actor.default-dispatcher-14] akka.remote.EndpointWriter - AssociationError [akka.tcp://Signer@127.0.0.1:5558] <- [akka.tcp://SignerConsole@127.0.0.1:42767]: Error [Shut down address: akka.tcp://SignerConsole@127.0.0.1:42767] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://SignerConsole@127.0.0.1:42767
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.**

This log have error: Error [Shut down address: akka.tcp://SignerConsole@127.0.0.1:42767] [
akka.remote.ShutDownAssociation: Shut down address: akka.tcp://SignerConsole@127.0.0.1:42767
Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.

**_- After start all service xroad, I start to send data from my SS to another SS but have error on proxy.log. This error below:_**

2021-02-26 16:59:01,202 [qtp1248276879-47] INFO  e.r.x.p.c.AbstractClientProxyHandler - Received request from 127.0.0.1
2021-02-26 16:59:01,772 [qtp1248276879-47] INFO  o.h.e.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
2021-02-26 16:59:01,773 [qtp1248276879-47] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Started.
2021-02-26 16:59:01,789 [qtp1248276879-47] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: ee.ria.xroad.common.db.CustomPostgreSQLDialect
2021-02-26 16:59:01,845 [qtp1248276879-47] INFO  o.h.e.j.e.i.LobCreatorBuilderImpl - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2021-02-26 16:59:01,846 [qtp1248276879-47] INFO  org.hibernate.type.BasicTypeRegistry - HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@24133127
2021-02-26 16:59:02,168 [qtp1248276879-47] INFO  o.h.h.i.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory
2021-02-26 16:59:03,040 [qtp1248276879-47-soap] ERROR e.r.x.p.c.ClientMessageProcessor - onError()
ee.ria.xroad.common.CodedException: IOError: null
        at ee.ria.xroad.common.ErrorCodes.translateException(ErrorCodes.java:212)
        at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:148)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.writeOcspResponses(ClientMessageProcessor.java:553)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor$SoapMessageHandler.soap(ClientMessageProcessor.java:485)
        at ee.ria.xroad.common.message.SoapMessageDecoder$MultipartHandler.body(SoapMessageDecoder.java:232)
        at org.apache.james.mime4j.parser.MimeStreamParser.parse(MimeStreamParser.java:133)
        at ee.ria.xroad.common.message.SoapMessageDecoder.readMultipart(SoapMessageDecoder.java:185)
        at ee.ria.xroad.common.message.SoapMessageDecoder.parse(SoapMessageDecoder.java:143)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.handleSoap(ClientMessageProcessor.java:448)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InterruptedIOException: null
        at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:275)
        at java.io.PipedInputStream.receive(PipedInputStream.java:231)
        at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
        at java.io.OutputStream.write(OutputStream.java:75)
        at ee.ria.xroad.common.util.MultipartEncoder.write(MultipartEncoder.java:185)
        at ee.ria.xroad.proxy.protocol.ProxyMessageEncoder.ocspResponse(ProxyMessageEncoder.java:146)
        ... 12 common frames omitted
2021-02-26 16:59:03,040 [qtp1248276879-47] ERROR e.r.x.p.c.AbstractClientProxyHandler - Request processing error (d6ebf893-4af8-4f01-bd5f-397af7ebbf9c)
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.InternalError: Connection reset
        at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:175)
        at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getOcspResponses(AuthTrustVerifier.java:155)
        at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verifyAuthCert(AuthTrustVerifier.java:109)
        at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verify(AuthTrustVerifier.java:92)
        at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.prepareAndVerify(FastestConnectionSelectingSSLSocketFactory.java:228)
        at ee.ria.xroad.proxy.clientproxy.FastestConnectionSelectingSSLSocketFactory.connectSocket(FastestConnectionSelectingSSLSocketFactory.java:169)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at ee.ria.xroad.common.util.HttpSender.doRequest(HttpSender.java:143)
        at ee.ria.xroad.common.util.HttpSender.doPost(HttpSender.java:99)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.sendRequest(ClientMessageProcessor.java:254)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.processRequest(ClientMessageProcessor.java:227)
        at ee.ria.xroad.proxy.clientproxy.ClientMessageProcessor.process(ClientMessageProcessor.java:188)
        at ee.ria.xroad.proxy.clientproxy.AbstractClientProxyHandler.handle(AbstractClientProxyHandler.java:94)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at ee.ria.xroad.common.util.CertHashBasedOcspResponderClient.getOcspResponsesFromServer(CertHashBasedOcspResponderClient.java:99)
        at ee.ria.xroad.common.util.CertHashBasedOcspResponderClient.getOcspResponsesFromServer(CertHashBasedOcspResponderClient.java:79)
        at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:172)
        ... 32 common frames omitted

I telnet to ocsp and tsa OK, telnet CS port 80, 4001 OK, telnet another SS port 5500, 5577 OK. 
Can you support me that Error?

Best regards,
Trungnv0412

**Comment by petkivim** [comment]
Hi @trungnv0412 

Could you provide the following information:

- host operating system and version
- X-Road version
- Java version

Best regards,
Petteri

**Comment by petkivim** [comment]
Hi @trungnv0412 

Based on the lines below, it seems like a connection problem between the Security Server and the OCSP service. The exceptions is thrown [here](https://github.com/nordic-institute/X-Road/blob/435e877eacd9002d0bfa72387dbdaf0cf6147b8b/src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AuthTrustVerifier.java#L175).

```
ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.InternalError: Connection reset
at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:175)
```

You could set the proxy logging level to `TRACE` or `ALL` to get mode details about the issue. Instructions for adjusting the logging level are available [here](https://confluence.niis.org/pages/viewpage.action?pageId=6783404).

Best regards,
Petteri

**Comment by trungnv0412** [comment]
Dear @petkivim 

Thank for your support!

**Comment by jjaone** [comment]
Hello,

I need to find out how to adjust logging levels and found the link above, but following that it says the page doe not exist, so where are to instrictuons to adjust log levels of individual SS service logs?

**Comment by raits** [comment]
Hello,

We have moved our confluence to the cloud, and unfortunately, the old links don't always redirect correctly. This page should give you the required information: https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4916392/How+to+change+Security+Server+logging+levels

**Comment by jjaone** [comment]
Thanks @raits the new link you provided is correct, am now able to change logging levels 💪

Do you happen to know which is the best log to follow when you want to know which other Security Servers try access our SS by making requests to 5500 and 5577 ports, is it the clientserver-proxy.log or..?
