### ISSUE TITLE
CS Not reconnect to Remote DB Postgres when timeout.

### ISSUE THREAD

**Issue by trungnv0412** [nordic-institute/X-Road#899]
Dear @petkivim !

I setup and config HA CS connect to Remote Database follow this document: https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md#4-general-installation-of-ha-support
- Server OS: ubuntu 18.04  lts 64 bit.
- Xroad Version 6.23.0

After my system setup and config complete, all are well. I run all function on https://CS:4000 and all is OK.
I recheck it after a period of time, when I login to https://CS:4000, my brower is hang, 

I get log on postgres :
centerui@centerui_production LOG:  could not receive data from client: Connection timed out

I get error log on nginx :
2021/02/26 17:39:45 [error] 37888#37888: *3 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: , request: "GET /login HTTP/1.1", upstream: "http://127.0.0.1:8083/login", host: "x.x.x.x:4000"

no error on jetty.log, if i restart jetty service, my system run well again.

In this case, what do i do to debug it?

Best regards,
trungnv0412

**Comment by petkivim** [comment]
Hi @trungnv0412 

You could try to make the Jetty logging more verbose by updating the logging level from `INFO` to `ALL`. Open `/etc/xroad/conf.d/jetty-logback.xml` for editing, change `<root level="INFO">` to `<root level="ALL">`, and restart jetty (`systemctl restart xroad-jetty`).

How much RAM does the hosting server have? 

Is there a process running that cleans up `/tmp` folder automatically? The Central Server uses `/tmp` folder to store temporary files and removing those files causes the application to crash.

Best regards,
Petteri

**Comment by trungnv0412** [comment]
Hi @petkivim 

2 servers setup HA CS:
CPU: 4 Core
RAM: 8GB
HDD: 100GB

2 server setup DB Postgres:
CPU: 16 Core
RAM: 16GB
HDD: 50 GB
storage : 250GB

I config  <root level="INFO"> to <root level="ALL"> and get error on jetty.log:

2021-03-01 11:17:01,832 [qtp1160003871-38] DEBUG o.e.j.util.thread.QueuedThreadPool - ran org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint@6fe3687b in QueuedThreadPool[qtp1160003871]@4524411f{STARTED,8<=8<=200,i=2,r=4,q=0}[ReservedThreadExecutor@31c31fa6{s=2/4,p=0}]
2021-03-01 11:17:11,171 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=780027} idle timeout check, elapsed: 30000 ms, remaining: 0 ms
2021-03-01 11:17:11,172 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=780028} idle timeout expired
2021-03-01 11:17:11,172 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@6907feb5{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:11,172 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@1030eae5{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:11,172 [Connector-Scheduler-7b69c6ba] DEBUG o.eclipse.jetty.io.AbstractEndPoint - Ignored idle endpoint SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=780028}
2021-03-01 11:17:11,264 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=180004} idle timeout check, elapsed: 30000 ms, remaining: 0 ms
2021-03-01 11:17:11,264 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=180004} idle timeout expired
2021-03-01 11:17:11,265 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@6dce0697{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:11,265 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@1ac88195{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:11,265 [Connector-Scheduler-7b69c6ba] DEBUG o.eclipse.jetty.io.AbstractEndPoint - Ignored idle endpoint SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=180005}
2021-03-01 11:17:41,172 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=810028} idle timeout check, elapsed: 30000 ms, remaining: 0 ms
2021-03-01 11:17:41,173 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=810029} idle timeout expired
2021-03-01 11:17:41,173 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@6907feb5{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:41,173 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@1030eae5{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:41,173 [Connector-Scheduler-7b69c6ba] DEBUG o.eclipse.jetty.io.AbstractEndPoint - Ignored idle endpoint SocketChannelEndPoint@7fdf736e{/127.0.0.1:58214<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@769f952a[p=HttpParser{s=END,0 of -1},g=HttpGenerator@72dfdc94{s=START}]=>HttpChannelOverHttp@457bc715{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.woff,age=810029}
2021-03-01 11:17:41,265 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=210005} idle timeout check, elapsed: 30000 ms, remaining: 0 ms
2021-03-01 11:17:41,265 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.IdleTimeout - SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=210005} idle timeout expired
2021-03-01 11:17:41,266 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.FillInterest - onFail FillInterest@6dce0697{null}
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:41,266 [Connector-Scheduler-7b69c6ba] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@1ac88195{IDLE}->null
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-01 11:17:41,266 [Connector-Scheduler-7b69c6ba] DEBUG o.eclipse.jetty.io.AbstractEndPoint - Ignored idle endpoint SocketChannelEndPoint@6d1bec5f{/127.0.0.1:58236<->/127.0.0.1:8083,OPEN,fill=-,flush=-,to=30000/30000}{io=0/0,kio=0,kro=1}->HttpConnection@23de6935[p=HttpParser{s=END,0 of -1},g=HttpGenerator@11951005{s=START}]=>HttpChannelOverHttp@25fb3b83{r=1,c=false,c=false/false,a=DISPATCHED,uri=//10.163.15.24:4000/stylesheets/fonts/opensans/OpenSans-Semibold-webfont.ttf,age=210006}


- folder /tmp not change.

Can you support me for this error?

Best regards,
trungnv0412

**Comment by petkivim** [comment]
Hi @trungnv0412 

The jetty debug level idle timeout exceptions in the log don't seem related so you can ignore them. Maybe the journal has some additional details:

```
sudo journalctl --no-pager -au xroad-jetty
```

You could also try to increase the Jetty metaspace from 160 to 200m. It can be done by adding the line below to `/etc/xroad/services/local.conf ` and restarting the `xroad-jetty` process after that.

```
JETTY_PARAMS="$JETTY_PARAMS -XX:MaxMetaspaceSize=200m "
```

Best regards,
Petteri

**Comment by trungnv0412** [comment]
Dear @petkivim !

I have tried the methods that you suggested above, but error not change. Now, I setup new system, 01 CS. If i config local database, my system run ok. But I change config remote database (Database setup on another server), I have the same error. I think I miss something when setup remote database. Have you got any suggested?

I get log database when my sytem timeout: 

2021-03-08 16:54:19.787 +07 [69719] centerui@centerui_production LOG:  could not receive data from client: Connection reset by peer
2021-03-08 17:34:52.353 +07 [68819] LOG:  received fast shutdown request
2021-03-08 17:34:52.354 +07 [68819] LOG:  aborting any active transactions
2021-03-08 17:34:52.354 +07 [69733] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.354 +07 [69743] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.354 +07 [69723] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.358 +07 [69736] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.358 +07 [69729] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.358 +07 [69732] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.358 +07 [69731] centerui@centerui_production FATAL:  terminating connection due to administrator command
2021-03-08 17:34:52.360 +07 [68819] LOG:  worker process: logical replication launcher (PID 68842) exited with exit code 1




2021-03-08 17:37:52.439 +07 [70909] LOG:  database system is ready to accept connections
2021-03-08 17:37:53.000 +07 [70948] [unknown]@[unknown] LOG:  incomplete startup packet
2021-03-08 19:50:02.850 +07 [71002] centerui@centerui_production LOG:  could not receive data from client: Connection timed out
2021-03-08 19:50:02.850 +07 [71003] centerui@centerui_production LOG:  could not receive data from client: Connection timed out
2021-03-08 19:50:02.850 +07 [71004] centerui@centerui_production LOG:  could not receive data from client: Connection timed out
2021-03-08 19:50:02.850 +07 [71006] centerui@centerui_production LOG:  could not receive data from client: Connection timed out
2021-03-08 19:50:02.850 +07 [71000] centerui@centerui_production LOG:  could not receive data from client: Connection timed out



Best regards,
trungnv0412

**Comment by petkivim** [comment]
Hi @trungnv0412 


Before the installation, have you completed all the steps described [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#26-remote-database-installation)?

What's the version of the remote PostgreSQL server that you're using?

Regards,
Petteri

**Comment by trungnv0412** [comment]
Dear @petkivim !

PostgreSQL version: 10.16
OS: ubuntu ubuntu0.18.04.1
I send you jetty.log:

[jetty.log](https://github.com/nordic-institute/X-Road/files/6114867/jetty.log)
