### ISSUE TITLE
Problem between Security Server and Test CA Server

### ISSUE THREAD

**Issue by jmhal** [nordic-institute/X-Road#954]
Hello  Community, 

I am installing X-Road services on AWS for learning purposes, following [Central Server Installation Guide](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md), I created the following instances with Ubuntu 20.04:

- cs: the Central Server
- ca: [Test-CA ](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md)(had to use Python 2.7 to make it work)
- ss0: a first Security Server.

All the machines are in the same security group, with ALL TRAFFIC permitted among them. Installation proceed smoothly for _cs_ and _ca_. I downloaded the anchor file for configuring _ss0_, but as soon as I added the time stamping server (Security Server/Settings/System Parameters) the following message appears on the Diagnostics:

Timestamping
Status | Service URL       | Message                      | Next Update
(red)   | https://ca:8899 | Internal error occurred | 16:19
OCSP Responders
Status | Service URL | Message | Previous Update | Next Update
(red)  | https://ca:8888 | Unable to connect to the OCSP responder | 16:18 | 16:38

So, it appears that the _ss0_ (Security Server) cannot communicate with the _ca_ machine. On _ss0_, /var/log/xroad/signer.log has the following message:

```
2021-05-01T19:23:51.122Z ERROR [Signer-akka.actor.default-dispatcher-6] e.r.x.s.certmanager.OcspClientWorker - Unable to connect to responder at https://ca:8888
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:448)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:184)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at ee.ria.xroad.signer.certmanager.OcspClient.createConnection(OcspClient.java:195)
        at ee.ria.xroad.signer.certmanager.OcspClient.createConnection(OcspClient.java:185)
        at ee.ria.xroad.signer.certmanager.OcspClient.fetchResponse(OcspClient.java:122)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.queryCertStatus(OcspClientWorker.java:312)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.handleExecute(OcspClientWorker.java:219)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.onReceive(OcspClientWorker.java:113)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-01T19:23:51.123Z WARN  [Signer-akka.actor.default-dispatcher-6] e.r.x.s.certmanager.OcspClientWorker - Received OCSP response that failed verification
java.lang.NullPointerException: null
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyResponseValidityCached(OcspVerifier.java:212)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidity(OcspVerifier.java:175)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidity(OcspVerifier.java:154)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.queryCertStatus(OcspClientWorker.java:339)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.handleExecute(OcspClientWorker.java:219)
        at ee.ria.xroad.signer.certmanager.OcspClientWorker.onReceive(OcspClientWorker.java:113)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-01T19:23:51.123Z INFO  [Signer-akka.actor.default-dispatcher-22] ee.ria.xroad.signer.OcspClientJob - OCSP-response refresh retry failed, continuing along backoff schedule
```

First I though it was a firewall or security group misconfiguration, but the following command appears to establish a connection:

```
ubuntu@ss0:/var/log/xroad$ curl https://ca:8888
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

I think there is something wrong with the certificates and the SSL setup. Are there any known incompatibilities for Test-CA under Ubuntu 20.04?

**Comment by petkivim** [comment]
Hi @jmhal 

The test TSA and OCSP only support `http`, `https` is not supported. Therefore, you should update the OCSP and TSA URLs from `https` to `http`. Please note that after changing the TSA URL you have reconfigure the TSA on the Security Servers (first remove, and then add again).

Best regards,
Petteri

**Comment by jmhal** [comment]
Hi @petkivim ,

Thank you for your reply. As you mentioned, in fact I was using _https_ instead of _https_. I changed that in the Central Server, created a new anchor file and tried to configure the Security Server again. I did not use the same virtual machine of the first Security Server, I created a new one. Now the Time Stamping service reports:

>  Connection ok, no timestamp request made yet 

but the OCSP responder says:

>  Status request not sent yet 

Both messages appear to be expected. But when I try to register the AUTH key I get:

>  error_code.core.Signer.InternalError
Member 'MEMBER:TRANSFORMACAODIGITAL/EDU/1000' has no suitable certificates
ID: c94f60d3bdde3962 

I am signing the certificates through the web interface. This is the log output in the Security Server:

```
2021-05-04T13:01:27.924Z ERROR [Signer-akka.actor.default-dispatcher-29] e.r.x.s.p.h.GetMemberSigningInfoRequestHandler - Certificate not suitable
ee.ria.xroad.common.CodedException: IncorrectValidationInfo: Signature on OCSP response is not valid
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyResponseValidity(OcspVerifier.java:245)
        at ee.ria.xroad.common.ocsp.OcspVerifier.lambda$verifyResponseValidityCached$0(OcspVerifier.java:213)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyResponseValidityCached(OcspVerifier.java:213)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidity(OcspVerifier.java:175)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidityAndStatus(OcspVerifier.java:138)
        at ee.ria.xroad.common.ocsp.OcspVerifier.verifyValidityAndStatus(OcspVerifier.java:121)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.verifyOcspResponse(GetMemberSigningInfoRequestHandler.java:135)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.checkValidity(GetMemberSigningInfoRequestHandler.java:121)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.isSuitableCertificate(GetMemberSigningInfoRequestHandler.java:108)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.selectMemberCert(GetMemberSigningInfoRequestHandler.java:90)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.handle(GetMemberSigningInfoRequestHandler.java:75)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.handle(GetMemberSigningInfoRequestHandler.java:56)
        at ee.ria.xroad.signer.protocol.AbstractRequestHandler.onReceive(AbstractRequestHandler.java:59)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
2021-05-04T13:01:27.928Z ERROR [Signer-akka.actor.default-dispatcher-29] e.r.x.s.p.AbstractRequestHandler - Error in request handler
ee.ria.xroad.common.CodedException: InternalError: Member 'MEMBER:TRANSFORMACAODIGITAL/EDU/1000' has no suitable certificates
        at ee.ria.xroad.common.CodedException.tr(CodedException.java:176)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.handle(GetMemberSigningInfoRequestHandler.java:78)
        at ee.ria.xroad.signer.protocol.handler.GetMemberSigningInfoRequestHandler.handle(GetMemberSigningInfoRequestHandler.java:56)
        at ee.ria.xroad.signer.protocol.AbstractRequestHandler.onReceive(AbstractRequestHandler.java:59)
        at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:332)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

What really bothers me is the _Signature on OCSP response is not valid_ message. It is as if the CA did not have the right certificates for the OCSP responder.

Any further tip?

**Comment by petkivim** [comment]
Hi @jmhal 

When you configured the Central Server, did you import the CA, TSA and OCSP certificates from /home/ca/CA/certs of the test-CA to the Central Server? The error message "Signature on OCSP response is not valid" suggests that the CA and OCSP certificates are not configured correctly on the Central Server.

Best regards,
Petteri

**Comment by jmhal** [comment]
Hi @petkivim ,

I reinstalled the TestCA, creating new ca.cert.pem, tsa.cert.pem, and ocsp.pem. Then I proceeded with registering the new CA on the Central Server, paying attention for using http instead of https. Now it seems to be working. 

Best Regards, 
jmhal
